### ISSUE TITLE
Cannot install generator-aspnetcore-spa on Ubuntu

### ISSUE THREAD

**Issue by bcanzanella** [aspnet/JavaScriptServices#1004]
```
$ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
```

```
$ sudo npm install -g yo generator-aspnetcore-spa
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/bin/yo -> /usr/lib/node_modules/yo/lib/cli.js
/usr/bin/yo-complete -> /usr/lib/node_modules/yo/lib/completion/index.js

> yo@1.8.5 postinstall /usr/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!

> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/generator-aspnetcore-spa/node_modules/spawn-sync
> node postinstall

module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/generator-aspnetcore-spa/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dev/.npm/_logs/2017-06-01T19_24_09_105Z-debug.log
```

**Comment by SteveSandersonMS** [comment]
The problem in your error log happened during the installation of the NPM module. This suggests there's an issue with the Node/NPM installation on your machine, or possibly just a temporary network problem. Either way, it's separate from the code in this repo, so there's nothing we could do here to fix it. If you just try again it might work (if it was a network issue); otherwise I'd suggest looking into reinstalling Node.
