### ISSUE TITLE
Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

### ISSUE THREAD

**Issue by uopeydel** [aspnet/JavaScriptServices#1008]
When I use cmd to run 
[dotnet new --install Microsoft.AspNetCore.SpaTemplates::*]
and
[dotnet new angular]
[npm install]
click file.csproj
save project
and I can run project net core angular it's perfect 
but when I publish to window server it show error below
How can I do?
**I try to do it in server 
1.reinstall node.js
2.run cmd [dotnet new --install Microsoft.AspNetCore.SpaTemplates::*] 
3.restart server
4.cmd [setx ASPNETCORE_ENVIRONMENT "Development"] and [setx ASPNETCORE_ENVIRONMENT "Development" /M]
5.rebuild project
not thing change error show below
Please help 
Thank much.

====================================

An error occurred while starting the application.

Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19)
at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30)
at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26)
at C:\Windows\TEMP\tmp68E8.tmp:113:19
at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38)
at emitNone (events.js:86:13)
Current directory is: D:\path\test-path
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19)
at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30)
at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26)
at C:\Windows\TEMP\tmp68E8.tmp:113:19
at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38)
at emitNone (events.js:86:13)
Current directory is: D:\path\test-path)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19) at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30) at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26) at C:\Windows\TEMP\tmp68E8.tmp:113:19 at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38) at emitNone (events.js:86:13) Current directory is: D:\path\test-path
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()

Show raw exception details
System.Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26)
    at C:\Windows\TEMP\tmp68E8.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: D:\path\test-path
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19) at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30) at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26) at C:\Windows\TEMP\tmp68E8.tmp:113:19 at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38) at emitNone (events.js:86:13) Current directory is: D:\path\test-path)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
AgentLine.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in Startup.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Show raw exception details
System.AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26)
    at C:\Windows\TEMP\tmp68E8.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: D:\path\test-path) ---> System.Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26)
    at C:\Windows\TEMP\tmp68E8.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: D:\path\test-path
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at AgentLine.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in D:\CORE\ok\AgentLine\Startup.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp67AE.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp67AE.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp67AE.tmp:62:26)
    at C:\Windows\TEMP\tmp68E8.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp68E8.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: D:\path\test-path
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()<---
.NET Core X64 v4.1.1.0    |   Microsoft.AspNetCore.Hosting version 1.1.0-rtm-22752    |    Microsoft Windows 6.3.9600    |   Need help?

**Comment by stephtr** [comment]
To me it seems like the npm packages didn't restore. How did you put your project onto the server? Did you also run `dotnet new angular` or did you just copy the files?
Depending on what you would like to achieve the best approach would usually be to run `dotnet publish --configuration release` locally and upload the resulting files to the server.

**Comment by uopeydel** [comment]
I put project to server by .. [In VSO2017 ]
1.I click select project in solution explorer
2.Click window 'Web Publish Activity'
3.Select my publish profile
4.it publish complete without error on client dev.

---

I have to try run [dotnet publish --configuration release]
in my folder sln project and refresh the page again
and click publish again
It have nothing change.

**Comment by SteveSandersonMS** [comment]
Your production server must be running the application in development mode. Don't do that :)

Make sure your deployed application runs in production mode. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

**Comment by beyazc** [comment]
you may be missing npm install

**Comment by AlwaysAbhl001** [comment]
>  Your production server must be running the application in development mode. Don't do that :)
> 
> Make sure your deployed application runs in production mode. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments

@SteveSandersonMS befor that it showing

```
An error occurred while processing your request.

Development Mode

Swapping to Development environment will display more detailed information about the error that occurred.
Development environment should not be enabled in deployed applications, as it can result in sensitive information from exceptions being displayed to end users.
```
After adding Development mode we facing this 

`Error was: Error: Cannot find module 'aspnet-webpack'`

let me know how to overcome this without adding Development mode in production.

**Comment by AlwaysAbhl001** [comment]
@uopeydel did you find any solution for this?
