### ISSUE TITLE
deployed to IIS window 10 failed to run

### ISSUE THREAD

**Issue by CLYeo** [aspnet/JavaScriptServices#1027]
hi,

I've publish the project using Visual Studio 2017 publish feature.
configure IIS and encountered this error when loading the site

Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Windows\TEMP\tmp6A62.tmp:83:19)
at __webpack_require__ (C:\Windows\TEMP\tmp6A62.tmp:20:30)
at createWebpackDevServer (C:\Windows\TEMP\tmp6A62.tmp:62:26)
at C:\Windows\TEMP\tmp6B1F.tmp:113:19
at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp6B1F.tmp:132:38)
at emitNone (events.js:86:13)
Current directory is: C:\Users\guest\Downloads\1)Published\newdotnetspa
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Windows\TEMP\tmp6A62.tmp:83:19)
at __webpack_require__ (C:\Windows\TEMP\tmp6A62.tmp:20:30)
at createWebpackDevServer (C:\Windows\TEMP\tmp6A62.tmp:62:26)
at C:\Windows\TEMP\tmp6B1F.tmp:113:19
at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp6B1F.tmp:132:38)
at emitNone (events.js:86:13)
Current directory is: C:\Users\guest\Downloads\1)Published\newdotnetspa)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack' at Function.Module._resolveFilename (module.js:469:15) at Function.Module._load (module.js:417:25) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Windows\TEMP\tmp6A62.tmp:83:19) at __webpack_require__ (C:\Windows\TEMP\tmp6A62.tmp:20:30) at createWebpackDevServer (C:\Windows\TEMP\tmp6A62.tmp:62:26) at C:\Windows\TEMP\tmp6B1F.tmp:113:19 at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp6B1F.tmp:132:38) at emitNone (events.js:86:13) Current directory is: C:\Users\guest\Downloads\1)Published\newdotnetspa
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()

**Comment by SteveSandersonMS** [comment]
In production, make sure your application runs in production mode, not development mode.
