### ISSUE TITLE
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied path.js:1142

### ISSUE THREAD

**Issue by shansfk** [aspnet/JavaScriptServices#1062]
I got this error

```
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/generator-aspnetcore-spa/node_modules/spawn-sync
> node postinstall

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1142
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:129:32)
    at bootstrap_node.js:542:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shanmugharajk/.npm/_logs/2017-06-25T16_35_05_657Z-debug.log
```

**Comment by SteveSandersonMS** [comment]
This is an issue with your Node installation, probably to do with permissions, though I can't say for sure. If you [search for the error message](https://www.google.co.uk/search?q=node+"getcwd%3A+cannot+access+parent+directories") there are a lot of reports of others fixing broken Node setups so one of the approaches they have used might work for you. Or as a first step, you might want to remove all traces of Node completely from your machine and reinstall it.

Since this is not something that could be fixed in this repo, I'll mark it closed. Hope that's OK!
