### ISSUE TITLE
dotnet new angular does not run after cloning from a repo (incorrect gitignore?)

### ISSUE THREAD

**Issue by PaluMacil** [aspnet/JavaScriptServices#1079]
On two different machines I ran `dotnet new angular` after having run `dotnet new --install Microsoft.AspNetCore.SpaTemplates::*`. I opened a PowerShell window as an administrator and then ran `dotnet restore` followed by `npm install`.

I did not have errors with restore or install, but running the project resulted in exceptions once I made a repo, added all, committed, and then cloned somewhere else.

**Version information**
```
C:\Source\vs\esap [master ≡]> node -v
v6.10.0
C:\Source\vs\esap [master ≡]> npm -v
4.3.0
C:\Source\vs\esap [master ≡]> dotnet --version
1.0.4
C:\Source\vs\esap [master ≡]> code --version
1.13.1
379d2efb5539b09112c793d3d9a413017d736f89
```
OmniSharp / C# plugin: 1.11.0
Windows 10
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Error**
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Call to Node module failed with error: Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (c:\Source\vs\temp\esap\webpack.config.js:36:27)
    at createWebpackDevServer (c:\Source\vs\temp\esap\node_modules\aspnet-webpack\WebpackDevMiddleware.js:178:31)
    at createWebpackDevServer (C:\Users\dcwol\AppData\Local\Temp\tmp9F53.tmp:74:50)
    at C:\Users\dcwol\AppData\Local\Temp\tmpA06E.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Users\dcwol\AppData\Local\Temp\tmpA06E.tmp:132:38)
    at emitNone (events.js:86:13)) ---> System.Exception: Call to Node module failed with error: Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (c:\Source\vs\temp\esap\webpack.config.js:36:27)
    at createWebpackDevServer (c:\Source\vs\temp\esap\node_modules\aspnet-webpack\WebpackDevMiddleware.js:178:31)
    at createWebpackDevServer (C:\Users\dcwol\AppData\Local\Temp\tmp9F53.tmp:74:50)
    at C:\Users\dcwol\AppData\Local\Temp\tmpA06E.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Users\dcwol\AppData\Local\Temp\tmpA06E.tmp:132:38)
    at emitNone (events.js:86:13)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at esap.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in c:\Source\vs\temp\esap\Startup.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at esap.Program.Main(String[] args) in c:\Source\vs\temp\esap\Program.cs:line 14
```

**Comment by PaluMacil** [comment]
Important note: I just repeated a couple times and it actually does work if I just create and run. However, it breaks when I create, push to a repo, and clone the repo. Something important must be in the gitignore but shouldn't be. I did notice that the wwwroot/dist/ folder is in the generated template but also ignored. Is there a reason for that?

**Comment by SteveSandersonMS** [comment]
You have to run Webpack to regenerate the `wwwroot/dist` and `ClientApp/dist` files if you don't have them. Run `webpack --config webpack.config.vendor.js` and then `webpack`.

In the next version of the templates, this is handled automatically by means of this code block in the `csproj` files: https://github.com/aspnet/JavaScriptServices/blob/dev/templates/ReactReduxSpa/ReactReduxSpa.csproj#L31 So, if you wanted, you could add that to your own `csproj` to make it run Webpack automatically when needed on build.
