### ISSUE TITLE
Webpack 3 compatibility

### ISSUE THREAD

**Issue by michaldudak** [aspnet/JavaScriptServices#1361]
Please consider making the `aspnet-webpack` package (and others such as `aspnet-webpack-react`) compatible with webpack 3. Currently yarn issues the following warnings:

```
warning "aspnet-webpack@2.0.1" has incorrect peer dependency "webpack@^1.13.2 || ^2.1.0-beta".
warning "aspnet-webpack-react@3.0.0" has incorrect peer dependency "webpack@^2.2.0".
```

However, despite these warnings, the packages seem to be working fine (although I have not tested them extensively).

**Comment by MovGP0** [comment]
confirmed. I have the same issue
```
warning "aspnet-webpack@2.0.1" has incorrect peer dependency "webpack@^1.13.2 || ^2.1.0-beta".
```

**Comment by MovGP0** [comment]
apparently the support for Webpack 3.0 does not work perfectly yet. When the server is still loading and a request already made, the request will be stuck waiting and canceled after the timeout of the cancellation token. 

After the server has fully loaded, additional requests will work fine. 

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```
(snipped stacktrace for clarity) 
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET https://localhost:4430/dist/styles.css
```

**Comment by Gimly** [comment]
I also tried updating to webpack 3.8.1 and I'm getting an exception when starting the app that says 

`Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'watchpack'`.

So I guess it's not fully compatible yet with webpack 3.x

**Comment by buvinghausen** [comment]
Gimly that's because you don't have node_modules in the expected folder nothing to do with webpack 3.x

**Comment by eyamenko-infotrack** [comment]
Webpack 3.8.1 works perfectly fine for me.

**Comment by jpisano** [comment]
Webpack 3.8.1 is working for me as well.

**Comment by jrmcdona** [comment]
Webpack 3.6 worked well for me
```

 "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@types/webpack-env": "1.13.0",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "core-js": "^2.5.1",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "json-server": "^0.12.0",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rimraf": "^2.6.2",
    "rxjs": "^5.5.2",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "to-string-loader": "^1.1.5",
    "typescript": "2.5.2",
    "url-loader": "^0.5.7",
    "webpack": "^3.6.0",
    "webpack-hot-middleware": "^2.19.1",
    "webpack-merge": "^4.1.0",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.2",
    "@ngtools/webpack": "^1.8.0",
    "@types/chai": "^3.4.34",
    "@types/jasmine": "^2.5.37",
    "chai": "^3.5.0",
    "codelyzer": "^4.0.0",
    "istanbul-instrumenter-loader": "^3.0.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.7.1",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.4",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^2.0.3",
    "protractor": "^5.1.2",
    "tslint": "^5.7.0",
    "webpack-bundle-analyzer": "^2.9.0"
  }
```

**Comment by Havret** [comment]
@eyamenko-infotrack, @jpisano, @jrmcdona 

How did you deal with warnings?

**Comment by eyamenko-infotrack** [comment]
@Havret just ignored them :)

**Comment by Havret** [comment]
@SteveSandersonMS Will you accept PR to remove this constraint?

**Comment by YannickRe** [comment]
@SteveSandersonMS It's fixed for "aspnet-webpack" but not for "aspnet-webpack-react"...

**Comment by SteveSandersonMS** [comment]
@YannickRe Thanks for the clarification!

**Comment by rjgotten** [comment]
And ofcourse Webpack 4 is now released, so can this be revisited to extend to Webpack 4?

**Comment by buvinghausen** [comment]
Webpack 3 was a near drop in replacement. Webpack 4 actually has a decent number of breaking changes.

**Comment by GeekyMonkey** [comment]
Angular 6 cli will ship with webpack 4.
