### ISSUE TITLE
The Angular CLI process times out first time debug is run 

### ISSUE THREAD

**Issue by paulsperanza** [aspnet/JavaScriptServices#1512]
When I run my app in development I  get the following exception. Refreshing the browser allows the app to run as expected.

System.TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 50 seconds. Check the log output for error information.
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.<WithTimeout>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.<PerformProxyRequest>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by agegould** [comment]
Hi.

We encounter the same behaviour which is due to the compilation of source files taking longer than the permitted timeout limit to connect to Node/Angular CLI.

If you refresh the browser it will eventually connect and you are good to go.
Once your source files are compiled the timeout no longer occurs.

Regards
Age Gould

**Comment by SteveSandersonMS** [comment]
@agegould is correct. And if you need to, you can change the timeout value by setting a value on the `spa.Options.StartupTimeout` property inside your `UseSpa` setup call.

**Comment by paulsperanza** [comment]
This worked for me. I set it to 80 seconds.
            app.UseSpa(spa =>
            {
                spa.Options.SourcePath = "ClientApp";

                if (env.IsDevelopment())
                {
                    spa.Options.StartupTimeout = new TimeSpan(0, 1, 20);
                    spa.UseAngularCliServer(npmScript: "start");
                }
            });

**Comment by JipingWang** [comment]
Not working for me, after added "spa.Options.StartupTimeout = new TimeSpan(0, 0, 80);"
Also, the message says "20 seconds?!!". 
`TimeoutException: The Angular CLI process did not start listening for requests within the timeout period of 20 seconds. `
Env:
VS2017 15.7 preview 5.0;
Windows 10 1709;
with Hyper-V;
Docker;

**Comment by SteveSandersonMS** [comment]
@JipingWang It's fixed in the latest code which should be included in the next ASP.NET Core preview release.

**Comment by JipingWang** [comment]
@SteveSandersonMS , good to know, thanks.

**Comment by fmorriso** [comment]
@JipingWang : As of 2018-07-13, using Visual Studio 2017 (15.7.5), Angular-CLI 6.0.8 and Angular 6.0.3, you _**still need**_ to override the default timeout value.  My example uses a admittedly _**extremely long / paranoid**_ value of 90 seconds, but feel free to adjust to your needs:
```C#
app.UseSpa(spa =>
	{
		spa.Options.SourcePath = "ClientApp";
		if (env.IsDevelopment())
		{
			spa.Options.StartupTimeout = new TimeSpan(days: 0, hours: 0, minutes: 1, seconds: 30);
			spa.UseAngularCliServer(npmScript: "start");
		}
	});
```

**Comment by iqmeta** [comment]
out of the box this takes ages.
just switched to ng serve on my own with visual studio code / terminal. now up an running ins seconds.

`spa.Options.StartupTimeout = new TimeSpan(0, 0, 360); 
//spa.UseAngularCliServer(npmScript: "start");
spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
`

**Comment by samson7s** [comment]
@SteveSandersonMS , good to know, thanks.
