### ISSUE TITLE
Non-Asp.net App

### ISSUE THREAD

**Issue by samcov** [aspnet/JavaScriptServices#1610]
I had an issue that was closed, and I couldn't reopen it, so I'm creating a new one.

There doesn't appear to be one single working non-asp.net example, and the advice isn't working. It does return the correct result, but in an error, and it appears that it's trapped in some **asp.net pipeline**.

The simplest solution would be to provide a working example, because I would hate to have to go over the network to do this when I really don't need to.

The info below comes from this issue [#1583](https://github.com/aspnet/JavaScriptServices/issues/1583)

@SteveSandersonMS , I get odd results. The add computation actually works, the right value is returned, but it's returned in the catch in the exception message, i.e. ex.Message = 42! 

It faults, and the issue is not in the javascript, but in nodeservices, and here is the full exception. Oddly, it looks like it's **behaving like an asp,net app in middleware pipline**!

   at Microsoft.AspNetCore.NodeServices.HostingModels.**HttpNodeInstance**.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NodeTestConsole.Program.<Add>d__5.MoveNext() in \JavaScriptServices-rel-2.0.0\NodeTestConsole\Program.cs:line 56

**Comment by SteveSandersonMS** [comment]
> There doesn't appear to be one single working non-asp.net example

There's one at https://github.com/aspnet/JavaScriptServices/tree/dev/samples/misc/LatencyTest

> Oddly, it looks like it's behaving like an asp,net app in middleware pipline!

Sorry, I'm not certain what you mean by that. In general, NodeServices runs a Node process in the background and dispatches calls to it via HTTP requests. That's why you're seeing `HttpNodeInstance` in the stack trace.

I'll close this because the linked sample does show a working example, but please let us know if you think that's not the case.

**Comment by samcov** [comment]
Steve, I do see the console app, but initially I didn't recognize it from the name of the project.

It works just fine, so I'll have to see what the differences are between that one and mine, but I'm sure that's the least of my worries now.

**Thanks** for solving this for me, this allows me to proceed with confidence!
