### ISSUE TITLE
Error with React SPA app and POST requests in Aspnet Core 2.1 rc1

### ISSUE THREAD

**Issue by istupakov** [aspnet/JavaScriptServices#1644]
### Functional impact
Strange error when do post request to react app hosted in aspnet core 2.1 rc1

### Minimal repro steps
1. `dotnet new react`
2. `dotnet publish`
3. run published version
4. Post request to localhost

### Expected result
Not Found 404
No error on server
### Actual result
Bad Request 400
Server Error:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found,
and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively
you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

### Further technical details
If run in dev mode (`dotnet run`) - everything work as expected.
```
dotnet --version
2.1.300-rc1-008673
```

**Comment by ymor** [comment]
When running the app with dotnet are you running it from the Release/netcoreapp2.0 folder?  If so you need to run it from the Release/netcoreapp2.0/publish folder.

**Comment by SteveSandersonMS** [comment]
Thanks for answering, @ymor. I expect your diagnosis is correct.
