### ISSUE TITLE
dotnet 2.1 RC crashes immediately after Angular SPA Build 

### ISSUE THREAD

**Issue by JohnGalt1717** [aspnet/JavaScriptServices#1649]
Looking at the logs immediately after the angular/cli dev server finishes building everything kestrel crashes:

Unhandled Exception: Unhandled Exception: System.AggregateException: One or more errors occurred. (An existing connection was forcibly closed by the remote host) ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.Shutdown()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.Abort()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.TransportConnection.Microsoft.AspNetCore.Connections.Features.IConnectionLifetimeFeature.Abort()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1OutputProducer.Abort(Exception error)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Abort(Exception error)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.Abort(Exception ex)
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   at System.IO.Pipelines.Pipe.<>c.<.cctor>b__79_2(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

This wasn't happening in Preview2.  Although downgrading doesn't help and nothing else has changed.

The project does build with ng build without issues and the debug console shows a successful build by ng serve.

If I manually run npm start and set UseSpa to use my manually created spa development server like so:

spa.UseProxyToSpaDevelopmentServer("http://localhost:4202");

It works fine and doesn't crash.  Which leads me to believe that this is an issue with JavaScriptServices.

**Comment by halter73** [comment]
Thanks for the report. This will be fixed in RTM. In the meantime, you can work around the issue by manually selecting the libuv transport https://github.com/aspnet/KestrelHttpServer/issues/2554#issuecomment-387894772.
