### ISSUE TITLE
asp-prerender-module breaks React's canUseDOM

### ISSUE THREAD

**Issue by nickdb93** [aspnet/JavaScriptServices#1657]
This is in reference to using OpenLayers to render a Map in .NET Core/React/Redux

### Title
*asp-prerender-module breaks React's canUseDOM*  
While `asp-prerender-module` is enabled, detecting whether or a component is rendering in the client becomes [seemingly] impossible. I've attempted the following methods:

1. `exenv` module's `canUseDOM` function: https://github.com/JedWatson/exenv
2. Detecting the window (i.e. `if (typeof window !== 'undefined') // render map`
3. Creating map in inside of `componentDidMount()`

### Functional impact
*Forces disabling of Server-Side Rendering application-wide*  
Would highly prefer to just disable rendering of that specific component, rather than disable SSR for teh whole application.

### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  

1. Run Dotnet CLI command `dotnet new reactredux` and then `npm install`
2. Install `openlayers` module and it's `types`, and `exenv`: 
          `$  npm i --save openlayers `
          `$  npm i --save @types/openlayers `
          `$  npm i --save exenv `
3. Target ES6: change `target` from `es5` to `es6` in `tsconfig.json`
4. Disable strict mode: set `"strict": false` in `tsconfig.json`
5. `import { canUseDOM } from 'exenv';` in `Home.tsx`
6. `import * as ol from 'openlayers';` in `Home.tsx`
7. Create map `<div>`: inside `render()`:
            `<div id="map" className="map" style={{ height: '500px' }}></div>`
8. Create map if `canUseDOM`:

```
        new ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM()
                })
            ],
            view: new ol.View({
                center: [0, 0],
                zoom: 3
            })
        });
```
9. `$  dotnet run `

### Expected result
*See OpenLayers Map render in Home*  

### Actual result
*Got `ReferenceError: window is not defined`*  
See below for full error. Would like guidance on how to accomplish my goals stated above. Thank you.

### Further technical details
*Full error stack*  

```
NodeInvocationException: Prerendering failed because of error: ReferenceError: window is not defined at xb.wb (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:632:723) at new xb (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:633:454) at C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:633:655 at OPENLAYERS (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:607:22) at Object.<anonymous> (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:613:2) at __webpack_require__ (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:20:30) at Object.<anonymous> (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:437:69) at __webpack_require__ (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:20:30) at Object.<anonymous> (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:243:75) at __webpack_require__ (C:\Users\nbaughman\source\Mercury\Jupiter\ClientApp\dist\main-server.js:20:30) Current directory is: C:\Users\nbaughman\source\Mercury\Jupiter
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper+<ProcessAsync>d__29.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner+<RunAsync>d__0.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
AspNetCore._Views_Home_Index_cshtml+<ExecuteAsync>d__12.MoveNext() in Index.cshtml
+
    ViewData["Title"] = "Home Page";
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageCoreAsync>d__16.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderPageAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Razor.RazorView+<RenderAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor+<ExecuteAsync>d__21.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
```

**Comment by nickdb93** [comment]
I have found a new, temporary workaround: import OpenLayers and instantiate the map inside `boot-client.tsx`. Would prefer a more clean solution, however. Still exploring other options.

**Comment by nickdb93** [comment]
# Solution

I'm fairly new to SSR with React, so I didn't really think about this. I ended up doing some exploring, however and found out the following:

I found it confusing that `import * as ol from 'openlayers'` did not throw an error when the `ol.Map` is not present in the component, when I was troubleshooting. This is because `import` is lazy by nature. 

Even though I was explicitly checking for the `window` (which is undefined when the server pre-renders), and even though I was constructing `ol.Map` inside of `componentDidMount()`, I was still getting `window is not defined.` **Turns out, even though `ol.Map` was not being created on the server, somehow it's very presence inside the component made the `import` statement get called on the server.** Thus, this is _not_ a bug. Just a detail I didn't think about when considering the 'lazy' nature of `import`.

I had been having trouble following suggestions of people in other threads who suggested to use `require` inside `componentDidMount()`, and calling `ol.Map` in `boot-client.ts` felt wrong. However, I was able to get it working. My full component is posted below.

## Code
```

import * as React from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { connect } from 'react-redux';
import { ApplicationState } from '../store';
import * as TrackMapStore from '../store/TrackMap';
import { TrackFeature, Coordinate } from '../store/TrackMap';

//////////////// important ////////////////////
let ol;


type TrackMapProps =
    TrackMapStore.TrackMapState
    & typeof TrackMapStore.actionCreators
    & RouteComponentProps<{}>;

const coord = {
    longitude: 0,
    latitude: 0
} as Coordinate;

const feat = {
    type: "Feature",
    geometry: {
        type: "Point",
        coordinates: [coord]
    },
    properties: {
        name: "hello"
    }
} as TrackFeature;


class TrackMap extends React.Component<TrackMapProps, {}> {
//////////////// important ////////////////////
    componentDidMount() {
        ol = require('openlayers');

        new ol.Map({
            renderer: 'dom',
            target: 'map',
            logo: false,
            loadTilesWhileAnimating: true,
            loadTilesWhileInteracting: true,
            layers: [
                new ol.layer.Tile({
                    source: new ol.source.OSM(),
                    preload: Infinity
                }),
            ],
            view: new ol.View({
                center: [0, 0],
                zoom: 5
            })
        });
    }
    public render() {
        return <div>
            <div>
                <button onClick={() => { this.props.add(feat) }}>ClickMe</button>
            </div>
            <div id="map" className="map"></div>
        </div>;
    }
}

export default connect(
    (state: ApplicationState) => state.features,
    TrackMapStore.actionCreators
)(TrackMap) as typeof TrackMap;

```
