### ISSUE TITLE
Exception on project startup when calling UseWebpackDevMiddleware

### ISSUE THREAD

**Issue by valentin-turcu** [aspnet/JavaScriptServices#1666]
Current project is targeting .NET Core 2.0, configured Webpack with Vue.js, everything works as expected with HMR. 

After following the migration guide at https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1 to move to .NET Core 2.1, the project builds but fails to start with the following exception:

> System.AggregateException: One or more errors occurred. (Unexpected response content type: text/html) ---> System.InvalidOperationException: Unexpected response content type: text/html
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at WebApp.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Projects\Git\TOPFAS\Develop\Source\NATO\EB\WebApps\WebApp\Startup.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.InvalidOperationException: Unexpected response content type: text/html
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)<---

My Main code:

public class Program

    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run(); // fail point
        }
        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }

My Startup code:
    public class Startup

    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            //services.Configure<CookiePolicyOptions>(options =>
            //{
            //    options.CheckConsentNeeded = context => true;
            //    options.MinimumSameSitePolicy = SameSiteMode.None;
            //});
            services.AddMvc();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true
                });
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            //app.UseCookiePolicy();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

                routes.MapSpaFallbackRoute(
                    name: "spa-fallback",
                    defaults: new { controller = "Home", action = "Index" });
            });
        }
    }

Commenting out the app.UseWebpackDevMiddleware block removes the exception (but also the HMR, naturally). 

Any ideas?

**Comment by valentin-turcu** [comment]
To add:
![cmd](https://user-images.githubusercontent.com/6671776/40785162-0992e0a6-64e8-11e8-9c0b-010ec4d61ce6.PNG)

Actual project is here:
[WebApp.zip](https://github.com/aspnet/JavaScriptServices/files/2058403/WebApp.zip)

**Comment by jakingfox** [comment]
I have the same problem.

**Comment by k-ta-yamada** [comment]
I solved it by adding `localhost` to the environment variable` no_proxy` when a similar error occurred.
(The environment is OSX and dotnet is version 2.0.6)

At that time, deserialization failed in the following places.

https://github.com/aspnet/JavaScriptServices/blob/release/2.0/src/Microsoft.AspNetCore.NodeServices/HostingModels/HttpNodeInstance.cs#L93

The reason for failing deserialization was that POST to localhost failed in the following places and probably HTML was returned as a response.

https://github.com/aspnet/JavaScriptServices/blob/release/2.0/src/Microsoft.AspNetCore.NodeServices/HostingModels/HttpNodeInstance.cs#L65

Originally, Json was not returned because `localhost` was not specified in the no_proxy environment variable.

I hope it will help resolve.
(I'm sorry if it has become unnatural text because it is translated by Google translation)
