### ISSUE TITLE
IIS deployment is not working

### ISSUE THREAD

**Issue by SARAVANA1501** [aspnet/JavaScriptServices#1747]
Hi,
I created new application in .Net core and Angular JS. I did on click publish to IIS server, it is not working.
I am getting the below mentioned error.

**project structure**

![image](https://user-images.githubusercontent.com/39718742/44590587-1a8d2680-a7d9-11e8-9b67-c45a67eb2c4b.png)

**My deployment folder**
![image](https://user-images.githubusercontent.com/39718742/44590635-3bee1280-a7d9-11e8-8c1f-dd20e38c2d06.png)

**Raw error detail:**

System.AggregateException: One or more errors occurred. (One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json'

npm ERR!  { [Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json']

)) ---> System.AggregateException: One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json'

npm ERR!  { [Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json']

) ---> System.InvalidOperationException: The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json'

npm ERR!  { [Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json']

 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.<>c.<Attach>b__2_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.SpaServices.Extensions.Util.TaskTimeoutExtensions.WithTimeout[T](Task`1 task, TimeSpan timeoutDelay, String message)
   at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
   at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Flex.EQ.UI.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in C:\TFSCorp\MPDM Tracker\Dev\Client\Flex.EQ.UI\Startup.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json'

npm ERR!  { [Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json']

) ---> System.InvalidOperationException: The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json'

npm ERR!  { [Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json']

 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.<>c.<Attach>b__2_0(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
---> (Inner Exception #0) System.InvalidOperationException: The NPM script 'start' exited without indicating that the Angular CLI was listening for requests. The error output was: npm ERR! Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json'

npm ERR!  { [Error: ENOENT, open 'D:\EQ\UI\node_modules\start\package.json']

 ---> System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SpaServices.AngularCli.AngularCliMiddleware.StartAngularCliServerAsync(String sourcePath, String npmScriptName, ILogger logger)<---
<---

**Comment by shilsmarty** [comment]
I got the same issue ? did we find ant solution ?

**Comment by boonmathew** [comment]
I am also facing the same. Please post the solution if you got this solved.

**Comment by addikhann** [comment]
SAME ISSUE :(

**Comment by boonmathew** [comment]
Hello Guys,
I spent dew days behind this and finally got solved. Since i am a newbie to angular this helped to learn many thins. :).
So my problem was actually the root path of Spafiles was different on Startup class.
`services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/dist/ClientApp";
            });`
First you need to check the out path in your angular.jsonj file
`"outputPath": "dist/ClientApp",`
and put the same in Startup class static file root path.

And mainly about the error, actually this error message is nothing related to our actuall error message. While deploying our application to a server already the all npm/ng build activities are done and VS will copy those file to the server. 
But if we have enabled the asp.net core environment as development mode in server then the following code will get executed in startup class.
`if (env.IsDevelopment())
                {
                    spa.UseAngularCliServer(npmScript: "start");
                }`
which shouldn't happen in server. So if you guys are deploying this application in development mode to server, try to comment out this line, then only you will get to know the actual error.
So .net is actually using this npm start(ng serve) to run the application in your local machine

**Comment by addikhann** [comment]
https://stackoverflow.com/questions/52724294/how-to-solve-the-npm-script-start-exited-without-indicating-that-the-angular-c        
i posted here today .. but no one reply my error.. please check
