### ISSUE TITLE
InvokeAsync getting cancelled after roughly 100 seconds

### ISSUE THREAD

**Issue by InvincibleDRT** [aspnet/JavaScriptServices#1778]
`await nodeServices.InvokeAsync<string>` is getting canclled after 100 seconds. getting `System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'` 

StackTrace
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AIRWAYS.Renderer.Processor.Utility.NodeUtility.<GenerateImage>d__0.MoveNext() in

**Comment by InvincibleDRT** [comment]
This is running on a background this which is queued with HostingEnvironment.QueueBackgroundWorkItem(x=>method());

**Comment by InvincibleDRT** [comment]
Invoked node service however continues to run in the background even after this exception

**Comment by InvincibleDRT** [comment]
Update: options.useSocketHosting() works for me...but that's package hasn't made it out of beta. Are there any plans to release that. It would be awesome if you can publish it
