### ISSUE TITLE
Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0

### ISSUE THREAD

**Issue by zigzag95** [aspnet/JavaScriptServices#209]
MacBook-Pro-de-neo:spa neo$ dotnet watch run
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Microsoft.DotNet.Watcher.Tools.Program.<>c__DisplayClass3_0.<MainInternal>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Watcher.Tools.Program.MainInternal(String[] args, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.Program.Main(String[] args)

**Comment by zigzag95** [comment]
solved after doing this:
https://github.com/aspnet/EntityFramework/issues/5458#issuecomment-221912806
