### ISSUE TITLE
How to include non-module javascript files in WebPack Server Side Compile

### ISSUE THREAD

**Issue by williamdstuart** [aspnet/JavaScriptServices#219]
I have an auto generated JavaScript file that was compiled from an autogenerated Typescript file that uses UMD namespaces (similar to TypeLite).
I am manually copying the javascript file to the /dist folder through web pack config file.
I have been able to get this to work in the client by adding a script tag in _layout.cshtml file. 

I can't seem to get it to be included in the server side code.  If I do this in the boot-server.ts file:
require("../proxy.js");
then I get the error message below.

I need to know the proper way to bring in an outside JavaScript file that makes use of global variables.  Another option is to disable the server side rendering, which is OK.

Thank you for your help!

Exception: Call to Node module failed with error: ReferenceError: Test is not defined
at <anonymous>:1805:39
at Object.c (<anonymous>:1810:3)
at __webpack_require__ (<anonymous>:20:30)
at Object.c (<anonymous>:1629:16)
at __webpack_require__ (<anonymous>:20:30)
at Object.<anonymous> (<anonymous>:56:17)
at __webpack_require__ (<anonymous>:20:30)
at <anonymous>:40:18
at Object.<anonymous> (<anonymous>:43:10)
at Module._compile (module.js:410:26)
at requireFromString (C:\Code\Test\Test-v1.0\Test\node_modules\require-from-string\index.js:27:4)
at C:\Code\Test\Test-v1.0\Clies.Test\node_modules\aspnet-webpack\LoadViaWebpack.js:75:42
at Compiler.<anonymous> (C:\Code\Test\Test-v1.0\Test\node_modules\webpack\lib\Compiler.js:194:14)
at Compiler.emitRecords (C:\Code\Test\Test-v1.0\Test\node_modules\webpack\lib\Compiler.js:282:37)
at Compiler.<anonymous> (C:\Code\Test\Test-v1.0\Test\node_modules\webpack\lib\Compiler.js:187:11)
at C:\Code\Test\Test-v1.0\Clies.Test\node_modules\webpack\lib\Compiler.js:275:11

**Comment by SteveSandersonMS** [comment]
Ideally you should reference your original TypeScript source code, not a specific JavaScript build of it. This is because Node and browsers have different module loading systems, and files built for one won't in general work in the other. This is why TypeScript supports different module output formats from the same `.ts` source code.

If you must use the pre-build .js file, I'm not sure how best you can make it work in Node, since it depends on exactly how it's compatible or otherwise with Node's module loading mechanisms.
