### ISSUE TITLE
If UseWebpackDevMiddleware gets back an error from Node during app startup, it fails to surface good error information

### ISSUE THREAD

**Issue by leak** [aspnet/JavaScriptServices#226]
Exception occures when adding `app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {HotModuleReplacement = true});` to Configure()

Node: 6.2.2
SpaServices: 1.0.0-beta-000009

`at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AurelaTestProject.Program.Main(String[] args) in D:\downloads\AurelaTestProject\src\AureliaTestProject\Program.cs:line 14`

**Comment by leak** [comment]
So i got this sorted. The exception is actually from here:
https://github.com/aspnet/JavaScriptServices/blob/dev/src/Microsoft.AspNetCore.NodeServices/HostingModels/HttpNodeInstance.cs#L66

But it did not bubble to the surface so I could actually read the actual message, so that might be something someone should look at.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting that! I'll look into whether we can better report exceptions that occur in that location.

**Comment by SteveSandersonMS** [comment]
In the current version, we do surface such errors (at least in the cases I'm aware of). If anyone can still repro disappearing error messages, please let us know!
