### ISSUE TITLE
Error: No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by leak** [aspnet/JavaScriptServices#228]
Not encountering this issue when running webpack manually from cmd.

Also, http://www.sobell.net/aurelia-error-no-module-factory-available-for-dependency-type-contextelementdependency/ did not help.

```
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.NodeServices[0]
      webpack building...
fail: Microsoft.AspNetCore.NodeServices[0]
      D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:181
                        return callback(new Error("No module factory available for dependency type: " + dependencies[i][0].constructor.name));
                         ^
fail: Microsoft.AspNetCore.NodeServices[0]
      Error: No module factory available for dependency type: ContextElementDependency
          at Compilation.addModuleDependencies (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:181:20)
          at Compilation.processModuleDependencies (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:170:7)
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:320:12
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:123:4
          at Array.forEach (native)
          at callback (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:122:12)
          at Compilation.<anonymous> (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\Compilation.js:140:10)
          at DependenciesBlock.<anonymous> (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\ContextModule.js:76:3)
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aurelia-webpack-plugin\dist\index.js:202:24
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\ContextModuleFactory.js:124:5
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\async\lib\async.js:52:16
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\async\lib\async.js:361:13
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\async\lib\async.js:52:16
          at done (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\async\lib\async.js:246:17)
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\async\lib\async.js:44:16
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\async\lib\async.js:358:17
          at D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\ContextModuleFactory.js:112:8
          at ContextModuleFactory.<anonymous> (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\tapable\lib\Tapable.js:82:11)
          at ContextModuleFactory.<anonymous> (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\dependencies\RequireContextPlugin.js:50:4)
          at ContextModuleFactory.<anonymous> (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\tapable\lib\Tapable.js:84:14)
          at ContextModuleFactory.<anonymous> (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\webpack\lib\dependencies\RequireContextPlugin.js:32:4)
          at ContextModuleFactory.applyPluginsAsyncWaterfall (D:\downloads\AurelaTestProject\src\AureliaTestProject\node_modules\aspnet-webpack\node_modules\tapable\lib\Tapable.js:86:13)
```

**Comment by MarkPieszak** [comment]
Did you globally install webpack & the aspnet one? @leak 

    npm i -g webpack aspnet-webpack

**Comment by leak** [comment]
webpack yes, is aspnet-webpack really requred globally?

**Comment by MarkPieszak** [comment]
I'm not positive but I know I have it, and haven't gotten your issue. Give it a shot.

**Comment by SteveSandersonMS** [comment]
I definitely wouldn't recommend installing `aspnet-webpack` globally (or any other NPM package that isn't itself a command-line tool). The only use case for NPM package being installed globally is if you're going to run them as command-line tools. If you do install random NPM package globally, then you don't necessarily even know what NPM package any given project is relying on to run correctly, and trying to upgrade or install a package for one project might break some completely unrelated project on your machine. If you might have randomly installed things globally in the past, then I suggest [removing them all](http://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally) and getting your machine back into a clean state. Sometimes people have problems that they solve by reinstalling Node itself or changing to a different version of Node, which is really just a very inconvenient way of emptying their set of global packages.

Anyway, [the "No module factory" error comes from webpack](https://github.com/search?q=org%3Awebpack+%22No+module+factory+available%22&type=Issues), but I don't know what causes it in your particular case. I've never had that error myself, nor do I know how to cause it if I wanted to. Do you have any way of reproing it in the absence of Aurelia?

**Comment by SteveSandersonMS** [comment]
I'll close this due to lack of info, but if anyone find out how to repro it, please let us know.

Note that pretty soon I'm hoping to add an Aurelia generator, so if this is something you inevitably hit with Aurelia, I'll probably discover it :)
