### ISSUE TITLE
Prerendering errors

### ISSUE THREAD

**Issue by dknaack** [aspnet/JavaScriptServices#282]
Ive create a ReactRedux application using the generator-aspnetcore-spa. If i run the app and go to localhost:5000 i get 

```
Error.
An error occurred while processing your request.

```
in the Browser and a lot of typescript errors like

```
// ...
// tons of TypeScript errors
// ...

ERROR in /Users/dknaack/Development/MyApp/bin/Debug/netcoreapp1.0/publish/node_modules/aspnet-prerendering/src/Prerendering.ts
(2,22): error TS2307: Cannot find module 'url'.

ERROR in /Users/dknaack/Development/MyApp/bin/Debug/netcoreapp1.0/publish/node_modules/aspnet-prerendering/src/Prerendering.ts
(3,23): error TS2307: Cannot find module 'path'.

ERROR in /Users/dknaack/Development/MyApp/bin/Debug/netcoreapp1.0/publish/node_modules/aspnet-prerendering/src/Prerendering.ts
(140,89): error TS2305: Module ''domain'' has no exported member 'Domain'.
    at /Users/dknaack/Development/MyApp/node_modules/aspnet-webpack/LoadViaWebpack.js:84:31
    at Compiler.<anonymous> (/Users/dknaack/Development/MyApp/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/dknaack/Development/MyApp/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/dknaack/Development/MyApp/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/dknaack/Development/MyApp/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/dknaack/Development/MyApp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/dknaack/Development/MyApp/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/Users/dknaack/Development/MyApp/node_modules/webpack/lib/Compiler.js:267:14)
    at /Users/dknaack/Development/MyApp/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/Users/dknaack/Development/MyApp/node_modules/webpack/node_modules/async/lib/async.js:236:30)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__12`1.MoveNext()
```

in the console.

So, the prerendering does not work on my machine.

Any ideas on how to fix this ?

**Comment by dknaack** [comment]
After reinstalling nodejs and npm it works.

**Comment by SteveSandersonMS** [comment]
I don't know why this directory exists: `/Users/dknaack/Development/MyApp/bin/Debug/netcoreapp1.0/publish/node_modules/`

There should be no reason to copy your `node_modules` into the `bin` folder. What did that? Did you run some sort of publishing action, or have you set up a custom build mechanism or build steps?

One quick resolution will be to exclude the `bin` folder in your `tsconfig.json`, e.g. change this:

```
  "exclude": [
      "node_modules"
  ]
```

to this:

```
  "exclude": [
      "bin",
      "node_modules"
  ]
```

But I'd also be interested to know why the `node_modules` directory got copied like that, assuming you have just created a new project as your issue report implies.
