### ISSUE TITLE
Webpack command fails after running the Aurelia template

### ISSUE THREAD

**Issue by pottereric** [aspnet/JavaScriptServices#436]
I am running on a windows machine and I was in an empty folder. I exectued the "yo aspnetcore-spa" command and selected "Aurelia". While yeoman was running I got the following error:

Error: Module 'c:\Projects\fwdevcon\audemo\node_modules\css\index.js' is not a loader (must have normal or pitch function)
    at loadLoader (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\loadLoader.js:35:10)
    at iteratePitchingLoaders (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at iteratePitchingLoaders (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:160:10)
    at c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:180:6
    at runSyncOrAsync (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:119:12)
    at c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:170:3
    at loadLoader (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:164:2)
    at runLoaders (c:\Projects\fwdevcon\audemo\node_modules\loader-runner\lib\LoaderRunner.js:357:2)
    at NormalModule.doBuild (c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\NormalModule.js:131:2)
    at NormalModule.build (c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\NormalModule.js:179:15)
    at Compilation.buildModule (c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\Compilation.js:127:9)
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\Compilation.js:306:10
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\tapable\lib\Tapable.js:123:70)
    at onDoneResolving (c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\NormalModuleFactory.js:49:11)
    at onDoneResolving (c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\NormalModuleFactory.js:165:6)
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\lib\NormalModuleFactory.js:161:6
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:3853:9
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:484:16
    at iteratorCallback (c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:1084:13)
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:988:16
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:3850:13
    at apply (c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:41:25)
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:76:12
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:484:16
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:1161:9
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:484:16
    at iteratorCallback (c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:1084:13)
    at c:\Projects\fwdevcon\audemo\node_modules\webpack\node_modules\async\dist\async.js:988:16
module.js:471

When I attempt to run the project with "dotnet run" I get errors becuase resources are missing from the dist directory.

**Comment by pottereric** [comment]
On my machine, the generator seems to work when I get webpack 2.1.0-beta.25 and it fails when I have 2.1.0-beta.27.

**Comment by MarkPieszak** [comment]
There are lots of hidden errors with certain versions of 2.* Webpack, for now I'd either stick with 1.* or -beta.25 if that works (it's what I've been sticking with for a while).

**Comment by SteveSandersonMS** [comment]
Thanks for letting us know about this!

Having the dependency on Webpack 2 beta does create risks like this, which is why most of the templates are sticking with Webpack 1 until v2 is properly released. Unfortunately the v2 dependency can't be avoided in the Aurelia template.

I've modified the Aurelia template `package.json` to strictly force its local copy of Webpack to be 2.1.0-beta.25 (not any later beta). We'll have to update this manually if some later beta turns out to be needed later. Hopefully Webpack v2 will ship for real soon!
