### ISSUE TITLE
Not compatible with Material (v2)

### ISSUE THREAD

**Issue by nimble99** [aspnet/JavaScriptServices#457]
After installing ng2 material, I get this error...

```
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: TypeError: Cannot read property 'toLowerCase' of undefined
at new StyleCompatibility (node_modules\@angular\material\material.umd.js:2250:59)
at AppView._View_NavMenuComponent0.createInternal (NavMenuComponent.ngfactory.js:101:35)
at AppView.create (node_modules\@angular\core\bundles\core.umd.js:9419:25)
at AppView._View_AppComponent0.createInternal (AppComponent.ngfactory.js:27:14)
at AppView.create (node_modules\@angular\core\bundles\core.umd.js:9419:25)
at AppView._View_AppComponent_Host0.createInternal (AppComponent_Host.ngfactory.js:17:14)
at AppView.create (node_modules\@angular\core\bundles\core.umd.js:9419:25)
at ComponentFactory.create (node_modules\@angular\core\bundles\core.umd.js:6029:40)
at ApplicationRef_.bootstrap (node_modules\@angular\core\bundles\core.umd.js:7051:44)
at node_modules\@angular\core\bundles\core.umd.js:6960:93
```

**Comment by MarkPieszak** [comment]
Unfortunately Material2 is still in Alpha and incompatible with Angular Universal, but, for now if you'd like, you can disable server-side rendering by removing the `asp-prerender-module` tag in your `/Views/Home/Index.cshtml` page, to get building things for now, and eventually be able to turn it back on once Material is compatible. 

(You can follow https://github.com/angular/material2/issues/308 to track the issue)

**Comment by nimble99** [comment]
Hi Mark,

Thanks for that. I'm _very_ new to ng as you can see - your pointer gets me moving.
Thanks

**Comment by MarkPieszak** [comment]
Glad to help, at least this way you can keep going in the Material direction you want, without having anything hold you back. Plenty of other things to work on until this is all resolved. 
Keep it up!

**Comment by SteveSandersonMS** [comment]
Thanks for answering @MarkPieszak!
