### ISSUE TITLE
react/MusicStore: SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by cveld** [aspnet/JavaScriptServices#458]
When trying out the react/MusicStore example I get the following exception after browsing to `http://localhost:5000`:

```
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: c:\examples\JavaScriptServices\samples\react\MusicStore\ReactApp\boot-server.js:138
import { fetch, addTask } from 'domain-task';
^^^^^^
SyntaxError: Unexpected token import
at Object.exports.runInThisContext (vm.js:78:16)
at Module._compile (module.js:545:28)
at requireFromString (c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\require-from-string\index.js:27:4)
at c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\aspnet-webpack\LoadViaWebpack.js:119:42
at Compiler.<anonymous> (c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:194:14)
at Compiler.emitRecords (c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:282:37)
at Compiler.<anonymous> (c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:187:11)
at c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:275:11
at Compiler.applyPluginsAsync (c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\tapable\lib\Tapable.js:60:69)
at Compiler.afterEmit (c:\examples\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:272:8)
```

I am using commit e3a4fad dated 14 November 2016 16:51:42.

Node -v
v7.1.0

How can I simulate the same behavior from the command-line without having to kick off `dotnet run`?
How can I fix the issue?

**Comment by cveld** [comment]
It appeared that I had some js files floating around in the folder structure (ReactApp/store/*.js) due to a typescript compile I had run to troubleshoot some issue I had earlier on. After removing the js files, webpack was able to kick off the right loaders. Maybe someone can explain to me what was going wrong here?

Additionally the following lines in `webpack.config.js` don't make sense to me; what are the semantics here?
```javascript
            { test: /\.ts(x?)$/, include: /ReactApp/, exclude: /node_modules/, loader: 'babel-loader' },
            { test: /\.ts(x?)$/, include: /ReactApp/, exclude: /node_modules/, loader: 'ts-loader' },
```

**Comment by SteveSandersonMS** [comment]
> Maybe someone can explain to me what was going wrong here?

It depends on how exactly you have compilation set up, but `.js` files can take precedence over `.ts` files for import, so I guess you had it loading the wrong files.

> Additionally the following lines in webpack.config.js don't make sense to me; what are the semantics here?

Webpack will apply all the matching loaders in sequence. Though awkwardly, in reverse order. So in this case, it's compiling your `.ts` files using `ts-loader` (probably to produce ES6 code - it depends on your `tsconfig.json`), then passing the output from that through `babel-loader` (probably to convert the ES6 code to ES3/ES5 code - depends on your `.babelrc`).
