### ISSUE TITLE
Cannot find module webpack.js error when deploying to azure

### ISSUE THREAD

**Issue by tomharris1** [aspnet/JavaScriptServices#468]
I built and ran the Angular2 template for Visual Studio via Yeoman. Everything runs fine locally, but when I do the git push to azure, I always get this error:

 Error: Cannot find module 'D:\home\site\repository\node_modules\webpack\bin\webpack.js'
     at Function.Module._resolveFilename (module.js:338:15)
     at Function.Module._load (module.js:280:25)
     at Function.Module.runMain (module.js:497:10)
     at startup (node.js:119:16)
     at node.js:906:3
 module.js:340
     throw err;
           ^
 Error: Cannot find module 'D:\home\site\repository\node_modules\webpack\bin\webpack.js'
     at Function.Module._resolveFilename (module.js:338:15)
     at Function.Module._load (module.js:280:25)
     at Function.Module.runMain (module.js:497:10)
     at startup (node.js:119:16)
     at node.js:906:3
 Project repository (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
 Compiling repository for .NETCoreApp,Version=v1.0

**Comment by tomharris1** [comment]
I can no longer re-create this so I'm closing it.  strange one.
