### ISSUE TITLE
Error building sample app

### ISSUE THREAD

**Issue by alcohen** [aspnet/JavaScriptServices#470]
I followed Steve Sanderson's very nice article "ASP.NET Core + Angular 2 template for Visual Studio". Everything seems OK, but when I try to run the project it complains and refuses to run (see stack trace below). So I'm filing an issue here as suggested in the article. Thanks!

---------------------------------------------

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
 Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
 at Function.Zone.assertZonePatched (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\zone.js\dist\zone-node.js:38:23)
 at new NgZoneImpl (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\@angular\core\bundles\core.umd.js:6219:18)
 at new NgZone (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\@angular\core\bundles\core.umd.js:6368:30)
 at PlatformRef_._bootstrapModuleFactoryWithZone (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\@angular\core\bundles\core.umd.js:6913:26)
 at PlatformRef_.bootstrapModuleFactory (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\@angular\core\bundles\core.umd.js:6904:25)
 at C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\angular2-platform-node\node-platform.js:439:38
 at tryCatch (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\aspnet-prerendering\node_modules\es6-promise\dist\es6-promise.js:410:12)
 at invokeCallback (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\aspnet-prerendering\node_modules\es6-promise\dist\es6-promise.js:425:13)
 at publish (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\aspnet-prerendering\node_modules\es6-promise\dist\es6-promise.js:393:7)
 at flush (C:\Users\Alan\Source\Repos\Angular2ApplicationTest\Angular2ApplicationTest\node_modules\aspnet-prerendering\node_modules\es6-promise\dist\es6-promise.js:121:5)

**Comment by nicwillemse** [comment]
Same issue for me, was working previously

**Comment by nicwillemse** [comment]
@alcohen, I have gotten around the issue by changing the dependency on Angular services to "1.0.0-beta-000019"

"Microsoft.AspNetCore.AngularServices": "1.0.0-beta-000019"

let me know if you come right ?

**Comment by McGune** [comment]
Same issue for me

**Comment by nicwillemse** [comment]
@McGune have you tried my solution above ?

**Comment by McGune** [comment]
Yes, it worked form me.

**Comment by hubert-associates** [comment]
Works. Thanks.

**Comment by hheexx** [comment]
You can eather block AngularServices on version 1.0.0-beta-000019 as advised here or apply patches from 28. nov.
https://github.com/aspnet/JavaScriptServices/commits/dev

**Comment by nicwillemse** [comment]
@hheexx Im not sure what that link is pointing out ?

**Comment by hheexx** [comment]
commits on this repository

**Comment by hheexx** [comment]
If you want to use AngularServices  1.0.0-beta-000020 or later you have to apply commits from 28.nov to template

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. Will publish a fix shortly.

**Comment by nicwillemse** [comment]
thanks @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
The fix is live now. Please update to version 1.0.0-beta-0000021 (or just go back to specifying 1.0.0-* but make sure it fetches the latest).

If you still get any issues please let me know!
