### ISSUE TITLE
VS Template w/Universal: Error

### ISSUE THREAD

**Issue by DoubleExposure** [aspnet/JavaScriptServices#535]
I decided to integrate the Customer Manager Angular2 application written by Dan Whalin into this VS 2015 template (ASP.NET Core + Angular 2 template for Visual Studio)
. I have a few pages wired up but to get it to work at all, I had to move the UniversalModule last instead of loading it first as required by the documentation. This hurts performance as you know. Why is it that the code breaks if UniversalModule loads first but works if it loads last?
The error in the browser console says --Failed to load resource: the server responded with a status of 500 (Internal Server Error). This occurs if the UniversalModule is loaded first.
The Angular2 error is a bit vague but is listed below:
Exception: Call to Node module failed with error: Error: This method is not implemented in Parse5DomAdapter: Parse5DomAdapter#getCookie
at _notImplemented (C:\Workspace\VSTestProject\VSTestProject\node_modules\angular2-platform-node\parse5-adapter.js:22:12)
at Parse5DomAdapter.getCookie (C:\Workspace\VSTestProject\VSTestProject\node_modules\angular2-platform-node\parse5-adapter.js:641:15)
at CookieXSRFStrategy.configureRequest (C:\Workspace\VSTestProject\VSTestProject\node_modules\@angular\http\bundles\http.umd.js:1597:92)
at XHRBackend.createConnection (C:\Workspace\VSTestProject\VSTestProject\node_modules\@angular\http\bundles\http.umd.js:1637:32)
at httpRequest (C:\Workspace\VSTestProject\VSTestProject\node_modules\@angular\http\bundles\http.umd.js:1975:24)
at Http.get (C:\Workspace\VSTestProject\VSTestProject\node_modules\@angular\http\bundles\http.umd.js:2086:20)
at DataService.getCustomers (C:\Workspace\VSTestProject\VSTestProject\ClientApp\dist\main-server.js:852:27)
at CustomersComponent.ngOnInit (C:\Workspace\VSTestProject\VSTestProject\ClientApp\dist\main-server.js:764:27)
at AppView._View_CustomersComponent_Host0.detectChangesInternal (CustomersComponent_Host.ngfactory.js:28:87)
at AppView.detectChanges (C:\Workspace\VSTestProject\VSTestProject\node_modules\@angular\core\bundles\core.umd.js:9566:18)

Any ideas?

**Comment by MarkPieszak** [comment]
It looks like Dans application is using Cookies, is that the part you're saying is causing the issue?

You're saying putting Universal last is hurting performance, in which way, initial server render?

**Comment by DoubleExposure** [comment]
Yes. Initial rendering.

**Comment by MarkPieszak** [comment]
Do you have a repo we can look at, hard to tell what exactly might be slowing it down. How much of a difference millisecond-wise, do you have any timers in there to record it?

**Comment by DoubleExposure** [comment]
I'll upload the code after the holidays.  Thanks

**Comment by SteveSandersonMS** [comment]
Thanks @MarkPieszak for responding.

Since this appears to be a support request rather than any bug in the JavaScriptServices code, I'll close this (we're following the approach of issues being open means there's some action to be taken on the code in this repo). But of course you can continue discussing it here nonetheless!

**Comment by DoubleExposure** [comment]
So since this is references http, does this mean that the UniversalModule has its own version of http module that should be used instead of the Angular2 Http module?

**Comment by MarkPieszak** [comment]
It simply overrides and hooks into all regular Http with its own version (needed to test for when the app becomes stable etc).

You can use the normal Http class though! Those things are just internal for Universal @DoubleExposure

**Comment by DoubleExposure** [comment]
Mark, I uploaded the file to OneDrive. 
https://1drv.ms/f/s!AizZOUdhmGGQigQE8uoOTCzd_tbj
