### ISSUE TITLE
npm install fails with vendor-manifest.json error

### ISSUE THREAD

**Issue by sirockin** [aspnet/JavaScriptServices#60]
When running npm install I get the following error (on both Windows and Mac) whether installing from yeoman or directly from git repo template:

Error: Cannot find module './wwwroot/dist/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Sirockin\Source\aspnet5\spa\test\webpack.config.js:33:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by SteveSandersonMS** [comment]
Can you tell me which versions of the DNX tools you're using?

 - Run `dnvm version` to get the version of that tool
 - Run `dnvm list` and see which item is marked as "active" to determine your runtime version
 - Run `dnx` and see the version given on the first line of the output

**Comment by sirockin** [comment]
`dnvm version` returns `1.0.0-rc1-15540`
`dnvm list` returns ` 1.0.0-rc1-final   clr     x86          win             default` as active row
`dnx` returns `Microsoft .NET Execution environment Clr-x86-1.0.0-rc1-16202`

**Comment by sirockin** [comment]
Discovered that failure was due to webpack not being globally installed. Suggest updating blog instructions accordingly.

**Comment by code4aman** [comment]
IMO, local webpack setup is more flexible solution

**Comment by SteveSandersonMS** [comment]
The templates now do use local webpack everywhere (both when first generating the project, and in the deployment scripts), so this issue should no longer apply.
