### ISSUE TITLE
sudden issue with webpack middleware

### ISSUE THREAD

**Issue by 0xFireball** [aspnet/JavaScriptServices#641]
webpack dev middleware was working perfectly fine, then I restarted my app and it stopped working.
Instead of webpack bundling the app like it usually does, I don't see any `webpack building` in the aspnetcore app log

I'm getting an error like this:
```
Hosting environment: Development
Content root path: C:\Users\nt\Documents\GitHub\PenguinUpload\PenguinUpload\src\PenguinUpload
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method PenguinUpload.Controllers.HomeController.Index (PenguinUpload) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\nt\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action PenguinUpload.Controllers.HomeController.Index (PenguinUpload) in 8240.4814ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 10604.5133ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/main.js?v=c5udZk132z7jyrQHN8Y4b7e2754AsxpDT9doDmlIK6A
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HL2BUP9JMSV2" communication error.
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 102077.807ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HL2BUP9JMSV2" communication error.
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081 ECANCELED operation canceled

```

the full current source to the application that is producing the error can be found here: <https://github.com/0xFireball/PenguinUpload/tree/dirstructure> (this is in the `dirstructure` branch)

If relevant, I'm using 
- Node 7.5.0
- dotnet `1.0.0-preview2-1-003177`
- at the time of posting, the latest version of all dependencies of my project

**Comment by 0xFireball** [comment]
I traced it down to the Webpack build hanging: `node node_modules/webpack/bin/webpack.js --config webpack.config.js`, so it probably isn't an issue with the middleware.

**Comment by stevescc** [comment]
@0xFireball Can I ask how you traced the issue down? I'm getting similar exceptions and am finding it really hard to work out what is wrong.

**Comment by dracan** [comment]
Likewise, I'm seeing exactly the same error. Did either of your work out the issue? @0xFireball @stevescc

**Comment by 0xFireball** [comment]
Yes, I managed to work it out; the issue was that the webpack build was hanging due to an error in compiling my Vue.js template. I found the problem by trying to run the webpack build by itself using `node node_modules/webpack/bin/webpack.js --config webpack.config.js`. In my case, the issue wasn't in JavaScriptServices but was instead with webpack failing to build.

**Comment by rajansen** [comment]
I believe you need to start your app and them make a small modification to your client files. I think its not always reloaded in memory on startup ?
