### ISSUE TITLE
yeoman+angular2: No ResourceLoader provided. Can't read url "counter.component.html"

### ISSUE THREAD

**Issue by jlost** [aspnet/JavaScriptServices#652]
Environment: 
`yo --version`: 1.8.5
aspnetcore-spa version: 0.8.1
`dotnet --version`: 1.0.0-preview2-1-003177

Steps to reproduce: 
`yo aspnetcore-spa`
`Angular 2.0.2`
`project.json`
`Y` (yes unit tests)
`anything` (project name)
`dotnet run`

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: Error: No ResourceLoader implementation has been provided. Can't read the url "counter.component.html"
    at Object._NO_RESOURCE_LOADER.get (E:\test-spa2\ClientApp\dist\vendor.js:43828:17)
    at DirectiveNormalizer._fetch (E:\test-spa2\ClientApp\dist\vendor.js:39786:45)
    at DirectiveNormalizer.normalizeTemplateAsync (E:\test-spa2\ClientApp\dist\vendor.js:39829:23)
    at DirectiveNormalizer.normalizeDirective (E:\test-spa2\ClientApp\dist\vendor.js:39804:46)
    at RuntimeCompiler._createCompiledTemplate (E:\test-spa2\ClientApp\dist\vendor.js:43218:210)
    at E:\test-spa2\ClientApp\dist\vendor.js:43156:43
    at Array.forEach (native)
    at E:\test-spa2\ClientApp\dist\vendor.js:43154:50
    at Array.forEach (native)
    at RuntimeCompiler._compileComponents (E:\test-spa2\ClientApp\dist\vendor.js:43153:45)
```

**Comment by jlost** [comment]
Duplicate #645
