### ISSUE TITLE
HMR does not work for react+redux template

### ISSUE THREAD

**Issue by sad1y** [aspnet/JavaScriptServices#654]
Im generate app using react+redux csproj 2017 and run it from console. May be it some how relates on #651 

```
e:\projects\temp\my>dotnet run
Hosting environment: Production
Content root path: e:\projects\temp\my
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method My.Controllers.HomeController.Index (My) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\maxit\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.css?v=drqKRA43vYEMTACwNml9OGCrx4DLsqCObMKs9Nf__b0
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action My.Controllers.HomeController.Index (My) in 3974.6254ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 4294.7885ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/dist/vendor.css'. Physical path: 'e:\projects\temp\my\wwwroot\dist\vendor.css'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/site.css?v=Lb5HSsGvBcEgLMQZ61Nva-Lpee8TNSEJ0mFBnX5PmbQ
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/dist/site.css'. Physical path: 'e:\projects\temp\my\wwwroot\dist\site.css'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 20.5426ms 200 text/css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/vendor.js?v=7DRIUpOebpX4lLgoWSWLN5fOB879OFqZERiNaCAtGss
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/dist/vendor.js'. Physical path: 'e:\projects\temp\my\wwwroot\dist\vendor.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/dist/main-client.js?v=mwoFzq4R7sFburv46yIny6UNwzzzsKSMdVi5Ppz9AiY
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/dist/main-client.js'. Physical path: 'e:\projects\temp\my\wwwroot\dist\main-client.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 67.6388ms 200 text/css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 9.1701ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 27.8167ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/__webpack_hmr?lastEventId=&r=1303430452328411
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method My.Controllers.HomeController.Index (My) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action My.Controllers.HomeController.Index (My) in 27.7949ms
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Call to Node module failed with error: Error: The location '/__webpack_hmr?lastEventId=&r=1303430452328411' doesn't match any route configured in react-router.
    at e:\projects\temp\my\ClientApp\dist\main-server.js:1062:23
    at e:\projects\temp\my\ClientApp\dist\vendor.js:56568:5
    at e:\projects\temp\my\ClientApp\dist\vendor.js:20804:11
    at next (e:\projects\temp\my\ClientApp\dist\vendor.js:20581:7)
    at loopAsync (e:\projects\temp\my\ClientApp\dist\vendor.js:20585:3)
    at matchRoutes (e:\projects\temp\my\ClientApp\dist\vendor.js:56831:29)
    at Object.match (e:\projects\temp\my\ClientApp\dist\vendor.js:20798:33)
    at match (e:\projects\temp\my\ClientApp\dist\vendor.js:56567:21)
    at e:\projects\temp\my\ClientApp\dist\main-server.js:1051:32
    at e:\projects\temp\my\ClientApp\dist\main-server.js:1049:12
System.Exception: Call to Node module failed with error: Error: The location '/__webpack_hmr?lastEventId=&r=1303430452328411' doesn't match any route configured in react-router.
    at e:\projects\temp\my\ClientApp\dist\main-server.js:1062:23
    at e:\projects\temp\my\ClientApp\dist\vendor.js:56568:5
    at e:\projects\temp\my\ClientApp\dist\vendor.js:20804:11
    at next (e:\projects\temp\my\ClientApp\dist\vendor.js:20581:7)
    at loopAsync (e:\projects\temp\my\ClientApp\dist\vendor.js:20585:3)
    at matchRoutes (e:\projects\temp\my\ClientApp\dist\vendor.js:56831:29)
    at Object.match (e:\projects\temp\my\ClientApp\dist\vendor.js:20798:33)
    at match (e:\projects\temp\my\ClientApp\dist\vendor.js:56567:21)
    at e:\projects\temp\my\ClientApp\dist\main-server.js:1051:32
    at e:\projects\temp\my\ClientApp\dist\main-server.js:1049:12
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper.<ProcessAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__31.MoveNext() in /Views/Home/Index.cshtml:line 2
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by SteveSandersonMS** [comment]
This line from your log:

    Hosting environment: Production

... shows that you're running in production mode. However, the fact that your client-side code is trying to make a request to `/__webpack_hmr` shows that your client-side code was built in development mode. This mismatch is what's causing the problem.

To avoid this, always build your client-side bundles in production mode before running the server in production mode. This happens automatically if you use `dotnet publish`, but if you've got some other manual way of deploying to a production-mode server, you'll need to run Webpack as follows first:

    webpack --config webpack.config.vendor.js --env.prod
    webpack --end.prod
