### ISSUE TITLE
Debugging broken for VS Code

### ISSUE THREAD

**Issue by jlost** [aspnet/JavaScriptServices#671]
This might be an issue for VS Code or OmniSharp or even the OmniSharp plugin for VS Code.

Generator version: 0.8.4
dotnet --version:  1.0.0-preview2-1-003177
VS Code version: 1.9.1

Steps to reproduce:
1. Use yeoman to make a new project with Angular 2.0.2 (w/ project.json)
2. code .
3. Hit f5

Error message:
```
An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Module build failed: Error: Final loader didn't return a Buffer or String
at E:\test-spa4\node_modules\webpack\lib\NormalModule.js:149:64
at E:\test-spa4\node_modules\loader-runner\lib\LoaderRunner.js:370:3
at iterateNormalLoaders (E:\test-spa4\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
at iterateNormalLoaders (E:\test-spa4\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
at E:\test-spa4\node_modules\loader-runner\lib\LoaderRunner.js:233:3
at context.callback (E:\test-spa4\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
at E:\test-spa4\node_modules\awesome-typescript-loader\src\index.ts:98:13
at process._tickCallback (internal/process/next_tick.js:103:7)
at Object.<anonymous> (E:\test-spa4\ClientApp\dist\main-server.js:73:7)
at __webpack_require__ (E:\test-spa4\ClientApp\dist\main-server.js:20:30)
at E:\test-spa4\ClientApp\dist\main-server.js:66:18
at Object.<anonymous> (E:\test-spa4\ClientApp\dist\main-server.js:69:10)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)
Current directory is: e:\test-spa4
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
```

**Comment by SteveSandersonMS** [comment]
To enable VS Code debugging, you also need to set a few values on the `launch.json` file that it generates so it knows how to run the project. There's a guide to setting up debugging here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-projects
