### ISSUE TITLE
Cannot run the React MusicStore sample

### ISSUE THREAD

**Issue by schucha** [aspnet/JavaScriptServices#683]
Following the readme for running the React MusicStore sample.

The site runs fine, however when i attempt to access it I am getting the following error message. 

Any help would be appreciated.

An unhandled exception has occurred while executing the request
System.Exception: Call to Node module failed with error: Error: Webpack compilation reported errors. Compiler output follows: Hash: 278c9dad6a1d7bacd315
Version: webpack 1.14.0
Time: 4223ms
            Asset    Size  Chunks             Chunk Names
webpack-output.js  113 kB       0  [emitted]  main

ERROR in C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\@types\react-router-redux\index.d.ts
(9,10): error TS2305: Module '"C:/workspaces/online/JavaScriptServices/samples/react/MusicStore/node_modules/@types/react-router/index"' has no exported member 'Location'.
    at C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\aspnet-webpack\LoadViaWebpack.js:111:31
    at Compiler.<anonymous> (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:194:14)
    at Compiler.emitRecords (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:282:37)
    at Compiler.<anonymous> (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:187:11)
    at C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:275:11
    at Compiler.applyPluginsAsync (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\tapable\lib\Tapable.js:60:69)
    at Compiler.afterEmit (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:272:8)
    at Compiler.<anonymous> (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\webpack\lib\Compiler.js:267:14)
    at C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\workspaces\online\JavaScriptServices\samples\react\MusicStore\node_modules\async\lib\async.js:236:30)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext() in C:\workspaces\online\JavaScriptServices\src\Microsoft.AspNetCore.NodeServices\HostingModels\HttpNodeInstance.cs:line 73

**Comment by SteveSandersonMS** [comment]
There have been some breaking changes in the TypeScript type definitions for React libraries, and the sample you mention hasn't yet been updated to account for them. It's not urgent because it doesn't affect the actual React templates (it's only a sample that not many people see). However we will fix it eventually.

In the meantime, if you're interested in updating the code or type definition dependencies to fix this, we'd gratefully accept a pull request!

**Comment by SteveSandersonMS** [comment]
This sample has been removed in the latest `dev` branch because it was out-of-date and not very useful. We probably don't need a newer equivalent to this sample, because the `AngularSpa` template itself is a more convincing application structure and provides good guidance on its own. It's not desirable to have detailed examples of third-party framework usage in this repo - documentation and samples about that should be maintained by the third-party framework teams themselves.
