### ISSUE TITLE
Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: localStorage is not defined 

### ISSUE THREAD

**Issue by jrmcdona** [aspnet/JavaScriptServices#691]
HI, 
I have an Angular, TypeScript, .NET Core app.  I am trying to also use https://github.com/btroncone/ngrx-store-localstorage.   However, I am getting this error which looks like it has to do with localStorage not being available in node.

Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: localStorage is not defined
at Object.exports.localStorageSync (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\node_modules\ngrx-store-localstorage\dist\index.js:104:41)

Do you know of any work arounds here?

Thanks

**Comment by jrmcdona** [comment]
Here is a full error stack.

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: localStorage is not defined
at Object.<anonymous> (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:1808:123)
at __webpack_require__ (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:20:30)
at Object.<anonymous> (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:177:19)
at __webpack_require__ (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:20:30)
at Object.<anonymous> (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:55:21)
at __webpack_require__ (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:20:30)
at C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:40:18
at Object.<anonymous> (C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin\ClientApp\dist\main-server.js:43:10)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
Current directory is: C:\Users\jordanmc\Source\Repos\Xbox.Ambassadors\Microsoft.Ambassadors.Admin\Microsoft.Ambassadors.Admin
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

**Comment by jrmcdona** [comment]
I am trying this https://github.com/aspnet/JavaScriptServices/issues/377

**Comment by dobrinsky** [comment]
Hi, 

I am trying to do the same thing and I am getting the same error.

The problem is I have Angular 4.3.6 and I have no 

import { isBrowser } from 'angular2-universal';

How did you managed to do it?

**Comment by kolte** [comment]
I am facing the same issue, did anyone solved it?

**Comment by 8bitreid** [comment]
same issue.  even used #377 still seeing this.
