### ISSUE TITLE
My Angular template is not working. (.net core)

### ISSUE THREAD

**Issue by gayan1991** [aspnet/JavaScriptServices#845]
Hi, I am trying to develop a web app using .net core angular 2 but I am having trouble running the app

```
Call to Node module failed with error: TypeError: Cannot read property 'publicPath' of undefined
at C:\Users\nadeeshag.NCS\node_modules\aspnet-webpack\WebpackDevMiddleware.js:99:59
at Array.forEach (native)
at Server.<anonymous> (C:\Users\nadeeshag.NCS\node_modules\aspnet-webpack\WebpackDevMiddleware.js:88:32)
at Server.g (events.js:286:16)
at emitNone (events.js:86:13)
at Server.emit (events.js:185:7)
at emitListeningNT (net.js:1279:10)
at _combinedTickCallback (internal/process/next_tick.js:71:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
at Microsoft.AspNetCore.NodeServices.HostingModels.<InvokeExportAsync>d__7.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNetCore.NodeServices.HostingModels.<InvokeExportAsync>d__13.MoveNext() 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 
at Microsoft.AspNetCore.NodeServices.<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
```

Any Idea why this issue is popping up. By the way, i am using webpack 2

**Comment by MarkPieszak** [comment]
Are you using the latest generator here? What changes have you made since the original? Check your git history on the webpack.config file its something there causing it potentially.

**Comment by SteveSandersonMS** [comment]
`WebpackDevMiddleware` tries to read `publicPath` from the `output` section of your Webpack config. If you (somehow) don't have an `output` section, you'd get this error. I don't think your Webpack config is likely to work without an `output` section anyway, so you probably should compare your config with a working one.

If you think there are scenarios where you wouldn't have an `output` section but this should still work, please file a separate issue with details. Thanks!

**Comment by gayan1991** [comment]
@SteveSandersonMS Thank you. Actually i found the issue. It's because I have another node modules list were installed inside my user folder. I have removed that folder and it started working.
