### ISSUE TITLE
Call to Node module failed with error: SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by JoshLefebvre** [aspnet/JavaScriptServices#866]
> System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at xxx.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\...\Startup.cs:line 69

> Inner Exception 1:
Exception: Call to Node module failed with error: SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.requireNewCopy (C:\Users\...\node_modules\aspnet-webpack\RequireNewCopy.js:16:16)
    at createWebpackDevServer (C:\Users\...\node_modules\aspnet-webpack\WebpackDevMiddleware.js:169:48)
    at createWebpackDevServer (C:\Users\...\AppData\Local\Temp\tmp7E29.tmp:74:50)

Trying to get hot reloading working for my solution that's using react with JSX and ES6. I keep getting the above error thrown at the following lines of code:
`app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
                {
                    HotModuleReplacement = true,
                    ReactHotModuleReplacement = true,
                    ConfigFile = "webpack.config.babel.js"
                });`
I have a feeling this has something to do with transpilation not occuring. Is there someway to pass in/use babel in this scenario if that is the case???

**Comment by casbeebc** [comment]
What version of Node are you using? Perhaps updating it will fix issues with ES6

**Comment by JoshLefebvre** [comment]
Just updated my version of Node. It was a little behind and now getting an inner exception that I don't believe was there the first time, but still seems to be the same issue that it does not know that this is ES6 and needs to be transpiled using babel: 

> {System.Exception: Call to Node module failed with error: C:\Users\...\webpack.config.babel.js:2
import webpack from 'webpack';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.requireNewCopy (C:\Users\...\node_modules\aspnet-webpack\RequireNewCopy.js:16:16)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()}

The import keyword being an ES6 standard

**Comment by SteveSandersonMS** [comment]
Please see Node docs to determine which specific features (e.g., ES6 `import` statements) are supported on which specific versions. Hope that's OK!

**Comment by huxaiphaer** [comment]
Did you get teh answer guys
