### ISSUE TITLE
Exception: Call to Node module failed with error: Error: Can't resolve all parameters for FetchDataComponent: (?).

### ISSUE THREAD

**Issue by AndrewKralovec** [aspnet/JavaScriptServices#867]
Sorry for the long post, i just wanted to give anyone kind enough to help a thorough explanation of what i did to get this error. 

I'm using the [Template Pack extension](https://visualstudiogallery.msdn.microsoft.com/31a3eab5-e62b-4030-9226-b5e4c9e1ffb5) for Visual Studio 2015 (not ready to make the jump to 2017) .  However, i wanted to update to the new version of angular instead of using 2.0.0, which comes with the template. So i copied over the package.json from the new [template](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa),  into my template, installed all the modules, restored the project, and run the application. Then this error appeared.  
![error](https://cloud.githubusercontent.com/assets/6210337/25046166/a238c6c8-20f5-11e7-8e0f-e3645e5cebe3.PNG)
![error_2](https://cloud.githubusercontent.com/assets/6210337/25046167/a23ab6b8-20f5-11e7-9949-0881f5bca15f.PNG)

So i thought it had to be the Webpack config files, so copied over the new webpack files and i get some type errors, which i dont think would break anything 
```
>webpack --config webpack.config.vendor.js
Everything is Fine
>webpack
Types errors 
```
Then i got the pre-rendering issue mentioned [here](https://github.com/aspnet/JavaScriptServices/issues/406), so i copied over the boot-server and boo.client-js which includes the mark's patch. Then decided to just copy over the entire Client-App folder to be sure. Deleted the Test folder/spec files, re-ran webpack commands, and finally I ran the application again to get the final and flowing error.

```
Exception: Call to Node module failed with error: Error: Can't resolve all parameters for FetchDataComponent: (?).
at SyntaxError.Error (native)
at SyntaxError.ZoneAwareError (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:74873:33)
at SyntaxError.BaseError [as constructor] (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:33353:20)
at new SyntaxError (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:33556:20)
at CompileMetadataResolver._getDependenciesMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50410:35)
at CompileMetadataResolver._getTypeMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50285:30)
at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:49925:28)
at CompileMetadataResolver._loadDirectiveMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:49801:27)
at C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50002:58
at Array.forEach (native)
at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50001:45)
at C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:59118:62
at Array.forEach (native)
at JitCompiler._loadModules (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:59117:47)
at JitCompiler._compileModuleAndComponents (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:59072:56)
```
The current project can be found [here](https://github.com/AndrewKralovec/Anuglar2Applcation). Thanks guys!!!

Full output

```
System.Exception: Call to Node module failed with error: Error: Can't resolve all parameters for FetchDataComponent: (?).
    at SyntaxError.Error (native)
    at SyntaxError.ZoneAwareError (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:74873:33)
    at SyntaxError.BaseError [as constructor] (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:33353:20)
    at new SyntaxError (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:33556:20)
    at CompileMetadataResolver._getDependenciesMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50410:35)
    at CompileMetadataResolver._getTypeMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50285:30)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:49925:28)
    at CompileMetadataResolver._loadDirectiveMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:49801:27)
    at C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50002:58
    at Array.forEach (native)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:50001:45)
    at C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:59118:62
    at Array.forEach (native)
    at JitCompiler._loadModules (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:59117:47)
    at JitCompiler._compileModuleAndComponents (C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\vendor.js:59072:56)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper.<ProcessAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__31.MoveNext() in /Views/Home/Index.cshtml:line 2
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultFilterAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllResultFiltersAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 28717.2442ms 500 text/html; charset=utf-8
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:63621/favicon.ico  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Information: The file /favicon.ico was not modified
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 106.327ms 304 image/x-icon
Microsoft.AspNetCore.NodeServices:Error: [at-loader] Checking finished with 27 errors
Microsoft.AspNetCore.NodeServices:Information: Node will restart because file changed: C:\Users\akralove\documents\visual studio 2015\Projects\Angular2Application\Angular2Application\ClientApp\dist\main-server.js
Microsoft.AspNetCore.NodeServices:Error: [at-loader] Checking finished with 27 errors
Microsoft.AspNetCore.NodeServices:Information: webpack built 8902d10d0e9923865e9e in 43331ms
Microsoft.AspNetCore.NodeServices:Information: Hash: 8902d10d0e9923865e9e
Version: webpack 2.3.3
Time: 43331ms
             Asset    Size  Chunks             Chunk Names
    main-client.js  128 kB       0  [emitted]  main-client
main-client.js.map  144 kB       0  [emitted]  main-client
chunk    {0} main-client.js, main-client.js.map (main-client) 98.6 kB [entry] [rendered]
    [0] delegated ./node_modules/@angular/core/index.js from dll-reference vendor_6d16e8a0e8055fc46d7d 42 bytes {0} [not cacheable] [built]
    [1] external "vendor_6d16e8a0e8055fc46d7d" 42 bytes {0} [not cacheable]
    [4] delegated ./node_modules/angular2-universal/browser/index.js from dll-reference vendor_6d16e8a0e8055fc46d7d 42 bytes {0} [not cacheable] [built]
    [5] ./ClientApp/boot-client.ts 1.3 kB {0} [built]
    [6] (webpack)-hot-middleware/client.js?path=http%3A%2F%2Flocalhost%3A53781%2F__webpack_hmr 6.68 kB {0} [built]
    [7] delegated ./node_modules/event-source-polyfill/eventsource.js from dll-reference vendor_6d16e8a0e8055fc46d7d 42 bytes {0} [not cacheable] [built]
   [10] ./ClientApp/app/app.module.ts 2.23 kB {0} [built]
   [28] ./~/querystring-es3/index.js 127 bytes {0} [built]
   [29] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [32] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
   [33] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
   [35] delegated ./node_modules/angular2-universal-polyfills/browser.js from dll-reference vendor_6d16e8a0e8055fc46d7d 42 bytes {0} [not cacheable] [built]
   [36] delegated ./node_modules/bootstrap/dist/js/npm.js from dll-reference vendor_6d16e8a0e8055fc46d7d 42 bytes {0} [not cacheable] [built]
   [37] delegated ./node_modules/webpack/buildin/module.js from dll-reference vendor_6d16e8a0e8055fc46d7d 42 bytes {0} [not cacheable] [built]
   [38] multi event-source-polyfill webpack-hot-middleware/client?path=http%3A%2F%2Flocalhost%3A53781%2F__webpack_hmr ./ClientApp/boot-client.ts 52 bytes {0} [built]
     + 24 hidden modules

ERROR in [at-loader] ./ClientApp/app/app.module.ts:30:14 
    TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in [at-loader] ./ClientApp/app/components/app/app.component.ts:8:14 
    TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in [at-loader] ./ClientApp/app/components/counter/counter.component.ts:7:14 
    TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in [at-loader] ./ClientApp/app/components/fetchdata/fetchdata.component.ts:8:14 
    TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in [at-loader] ./ClientApp/app/components/home/home.component.ts:7:14 
    TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in [at-loader] ./ClientApp/app/components/navmenu/navmenu.component.ts:8:14 
    TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in [at-loader] ./ClientApp/boot-server.ts:13:16 
    TS2693: 'Promise' only refers to a type, but is being used as a value here.

ERROR in [at-loader] ./node_modules/@angular/common/src/directives/ng_class.d.ts:48:34 
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:24:15 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:28:16 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/core/src/di/reflective_provider.d.ts:87:123 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/core/src/di/reflective_provider.d.ts:87:165 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/core/src/facade/lang.d.ts:12:17 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/core/src/facade/lang.d.ts:13:17 
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/@angular/http/src/headers.d.ts:52:59 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/http/src/url_search_params.d.ts:46:16 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts:79:33 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts:97:42 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts:22:37 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts:11:30 
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts:22:30 
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/angular2-universal/common/index.d.ts:1:33 
    TS2304: Cannot find name 'WeakMap'.

ERROR in [at-loader] ./node_modules/angular2-universal/node_modules/angular2-platform-node/node-platform.d.ts:14:20 
    TS2304: Cannot find name 'WeakMap'.

ERROR in [at-loader] ./node_modules/angular2-universal/node_modules/angular2-platform-node/node-renderer.d.ts:9:37 
    TS2304: Cannot find name 'Map'.

ERROR in [at-loader] ./node_modules/angular2-universal/node_modules/angular2-platform-node/node-shared-styles-host.d.ts:3:17 
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/angular2-universal/node_modules/angular2-platform-node/node-shared-styles-host.d.ts:10:17 
    TS2304: Cannot find name 'Set'.

ERROR in [at-loader] ./node_modules/rxjs/Observable.d.ts:69:60 
    TS2693: 'Promise' only refers to a type, but is being used as a value here.
The thread 0x1cf0 has exited with code 0 (0x0).
The thread 0x9c4 has exited with code 0 (0x0).
The thread 0x15a4 has exited with code 0 (0x0).
The thread 0xee4 has exited with code 0 (0x0).
The thread 0x1b40 has exited with code 0 (0x0).
```

**Comment by MarkPieszak** [comment]
It's not a simple upgrade process as universal has been moved to Core, you must use typescript 2.2+ and many other misc changes needed.  Working prototype [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal), might be able to add in the necessary changes here as well, but it's quite a difference now.

**Comment by SteveSandersonMS** [comment]
@MarkPieszak Thanks for answering!

**Comment by AndrewKralovec** [comment]
@MarkPieszak Sorry, I missed the notification. Thanks, I will check your prototype out. I appreciate you taking the time to look at my question.
