### ISSUE TITLE
The "ResolvePackageDependencies" task failed unexpectedly.

### ISSUE THREAD

**Issue by JordanMarr** [aspnet/JavaScriptServices#871]
After running "yo aspnetcore-spa" and creating an Aurelia (or Angular) .csproj for VS 2017, I get this error message immediately upon opening the project in VS.

Full error:
MSB4018	The "ResolvePackageDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.NET.Build.Tasks.LockFileCache.LoadLockFile(String path)
   at Microsoft.NET.Build.Tasks.LockFileCache.GetLockFile(String path)
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.get_LockFile()
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ReadProjectFileDependencies()
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by JordanMarr** [comment]
Additional info:
The project built without errors at first after running "yo aspnetcore-spa".  But I started receiving this error at some point after running the app.  I deleted the project and started over and it was the same thing:  it worked initially, but then I started getting the error again (no changes were made).

**Comment by MarkPieszak** [comment]
Do you have the latest VS2017 installed or some RC version of it perhaps?

**Comment by JordanMarr** [comment]
From the VS2017 About dialog:
Microsoft Visual Studio Professional 2017
Version 15.1 (26403.3) Release

So it is not a RC.

**Comment by SteveSandersonMS** [comment]
@JordanMarr I think you must be running an old version of `generator-aspnetcore-spa`. Can you please update to the latest and try again? Or can you confirm what version of `generator-aspnetcore-spa` you have?

Your error sounds like the same thing that was reported here: https://github.com/aspnet/JavaScriptServices/issues/620
