### ISSUE TITLE
Getting an error when running self-contained aspnetcore-spa application in Win7-x64

### ISSUE THREAD

**Issue by ekashkash** [aspnet/JavaScriptServices#877]
I'm new to ASP.NET CORE and Angular2. I have generated a new application using Yo w/ aspnetcore-spa template. Everything works fine when running the application from project root folder. It also works fine when I publish a self-contained version for osx.10.12-x64 version on mac. However, I'm getting an error when I publish the same project (with -r win7-x64) on Windows7. Here is the error I'm getting:

Unhandled Exception: System.AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware
failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ekashkas\AppData\Local\Temp\tmp3DED.tmp:83:19)
    at __webpack_require__ (C:\Users\ekashkas\AppData\Local\Temp\tmp3DED.tmp:20:30)
    at createWebpackDevServer (C:\Users\ekashkas\AppData\Local\Temp\tmp3DED.tmp:62:26)
    at C:\Users\ekashkas\AppData\Local\Temp\tmp3E99.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Users\ekashkas\AppData\Local\Temp\tmp3E99.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: C:\Work\Samples\VS\web_demo4\bin\release\netcoreapp1.1\Win7-x64\publish) ---> System.Exception: Call to Node module fa
iled with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'asp
net-webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\ekashkas\AppData\Local\Temp\tmp3DED.tmp:83:19)
    at __webpack_require__ (C:\Users\ekashkas\AppData\Local\Temp\tmp3DED.tmp:20:30)
    at createWebpackDevServer (C:\Users\ekashkas\AppData\Local\Temp\tmp3DED.tmp:62:26)
    at C:\Users\ekashkas\AppData\Local\Temp\tmp3E99.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Users\ekashkas\AppData\Local\Temp\tmp3E99.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: C:\Work\Samples\VS\web_demo4\bin\release\netcoreapp1.1\Win7-x64\publish
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions
options)
   at WebApplicationBasic.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Work\Sampl
es\VS\web_demo4\Startup.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplicationBasic.Program.Main(String[] args) in C:\Work\Samples\VS\web_demo4\Program.cs:line 14

Node version: v6.10.1
NPM version: 4.4.4
Any idea why this error occurs? please help.

**Comment by SteveSandersonMS** [comment]
When running a production build of your application, you must not try to enable hot module replacement (HMR), because that's only supported in dev builds.

Make sure your production app is running with the `ASPNETCORE_ENVIRONMENT` env var set to `Production` (or at least, *not* set to `Development`).

**Comment by ekashkash** [comment]
That worked, thank you!
