### ISSUE TITLE
Can not run on Local IIS with ASPNETCORE_ENVIRONMENT set to Development

### ISSUE THREAD

**Issue by martinfletcher** [aspnet/JavaScriptServices#883]
I have a new Angular app creates with the spa templates which I need to run on Local IIS on developer machines, with the ASPNETCORE_Environment variable set to Development.

With this set, i get the following error:

Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

Is there any solution to this?

**Comment by ADefWebserver** [comment]
It works fine on my machine if I first "publish" the application (In Visual Studio 2017 select Build then Publish).

See: [Publishing and Running ASP.NET Core Applications with IIS ](https://weblog.west-wind.com/posts/2016/Jun/06/Publishing-and-Running-ASPNET-Core-Applications-with-IIS) 

> ...If you absolutely have to run with IIS, you can publish the application to a local folder first, then configure an IIS virtual directory or site and use that to run your site...

**Comment by martinfletcher** [comment]
That is corect in that it still runs, but not in Development mode. It is is Production mode.

I need to set the ASPNETCORE_Environment variable to Development so that it runs correctly on dev server.

Any info would be great.

**Comment by SteveSandersonMS** [comment]
@martinfletcher Have you got repro steps that work on a clean machine? i.e., how exactly did you set up IIS to serve your application? It sounds like the IIS process is running with the wrong working directory, or something like that, which means it doesn't see your `node_modules` directory.

**Comment by martinfletcher** [comment]
@SteveSandersonMS Thanks, I had already done that, but still did not work.

I discovered (from the source code) that http binding is required for aspnet-webpack (hard coded localhost on http).

I take it this will now break if i have require https filters in place? Is there specific urls that i can exclude from this, or ideally a better way of not having to have http binding for my app?

**Comment by martinfletcher** [comment]
Apologies, this is the correct issue, not #227

**Comment by SteveSandersonMS** [comment]
Are you saying that adding an http binding fixes it? What part of the source code are you referring to>

If adding an http binding in your IIS config fixes it, I'm surprised by that, since the only thing that HMR is doing with this is telling a local instance of Webpack dev middleware to listen for requests on `http://localhost:someport`, which should be completely independent of IIS (it's a separate, standalone server).

**Comment by martinfletcher** [comment]
Sorry, red herring..... I still had ASPNETCORE_ENVIRONMENT=Production

What I am trying to achieve is to deploy my web app to Local IIS so that it can be targeted by another app without having to un 2 instances of visual studio and reference localhost:xxxxx etc

Basically here is what I have to achieve this:

Web app created using dotnet new angular (Spa Templates)
Publish (Debug build) to Local IIS
App Pool (No Managed Code)
Site pointing to correct directory
Site has ASPNETCORE_ENVIRONMENT=Development set

I am getting the following error when ASPNETCORE_ENVIRONMENT=Development:

System.AggregateException: One or more errors occurred. (Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp7FA2.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp7FA2.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp7FA2.tmp:62:26)
    at C:\Windows\TEMP\tmp804F.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp804F.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: S:\dev\pub\BackOffice.Presentation.Web) ---> System.Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp7FA2.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp7FA2.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp7FA2.tmp:62:26)
    at C:\Windows\TEMP\tmp804F.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp804F.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: S:\dev\pub\BackOffice.Presentation.Web
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at BackOffice.Presentation.Web.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in S:\dev\BackOffice\src\BackOffice.Presentation.Web\Startup.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) System.Exception: Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Windows\TEMP\tmp7FA2.tmp:83:19)
    at __webpack_require__ (C:\Windows\TEMP\tmp7FA2.tmp:20:30)
    at createWebpackDevServer (C:\Windows\TEMP\tmp7FA2.tmp:62:26)
    at C:\Windows\TEMP\tmp804F.tmp:113:19
    at IncomingMessage.<anonymous> (C:\Windows\TEMP\tmp804F.tmp:132:38)
    at emitNone (events.js:86:13)
Current directory is: S:\dev\pub\BackOffice.Presentation.Web
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()<---

**Comment by patrickgomes1968** [comment]
Noob-alert! :)
I have the identical issue and my ASPNETCORE_ENVIRONMENT = 'Development'.
My app was working just fine for a week until today. I git reset to discard all changes in working directory from when it last worked okay. To no avail. 
No I don't see a node_modules folder in my MVC project, but I tried copying it from another project, along with the webpack file, but it didn't help. Do I need to generate it somehow? Please help.
repo:  [((https://github.com/patrickgomes1968/vega))]
 exception:
`   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossi
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCancele
s)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotific
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware
ionBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at Vega.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env,
nv, ILoggerFactory lo
ggerFactory) in C:\Users\Patrick\Desktop\Tech Studies\ASP-Projects\vega\Sta-
rtup.cs:line 55
--- End of stack trace from previous location where exception was thrown --atio
   at Vega.Startup.Configure(IApplicationBuilder app, IHostingEnvironment e
der app, IHostingEnvironment env, ILoggerFact\Patrick\Desktop\Tech Studies\
ory loggerFactory) in C:\Users\Patrick\Deskto                              dies
p\Tech Studies\ASP-Projects\vega\Startup.cs:l where exception was thrown --
ine 55
--- End of stack trace from previous locationionDispatchInfo.Throw()
 where exception was thrown ---              BasedStartup.Configure(IApplic
   at System.Runtime.ExceptionServices.Except
ionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicatio
nBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Vega.Program.Main(String[] args) in C:\Users\Patrick\Desktop\Tech Studies
\ASP-Projects\vega\Program.cs:line 15
`

**Comment by ADefWebserver** [comment]
patrickgomes1968 Can you re-install the templates (just run `dotnet new --install Microsoft.AspNetCore.SpaTemplates::*` again) and create a new project and see if that works?

**Comment by patrickgomes1968** [comment]
@ADefWebserver : Thanks. Re-installed them. Created a new proj. But still getting the same exception(s).
Would it have made a difference that I tried running my old project first after re-installing the templates?

**Comment by ADefWebserver** [comment]
@patrickgomes1968 : I do not think running your old project made a difference. The only other thing I can suggest is un-installing and re-installing Node.

**Comment by SteveSandersonMS** [comment]
@patrickgomes1968 It sounds like your Node.js setup is pretty messed up. If I was in your situation, I'd purge every trace of Node (including `node_modules` directories anywhere - a common mistake is somehow getting a `node_modules` directory in your home folder, or hard drive root, which then interferes with NPM everywhere) and reinstall it. Disclaimer: back up your stuff; deleting things is your own choice :)

Both the @patrickgomes1968 and @martinfletcher reports appear to be due to problematic Node installations, which is outside the scope of this repo, so I'll close this. Hope that's OK!

**Comment by beyazc** [comment]
@patrickgomes1968 you can not run procution publish with environment variable indicating development for angular project
