### ISSUE TITLE
Unknown plugin "react-transform" in ./ClientApp/boot-client.tsx

### ISSUE THREAD

**Issue by aorlenko** [aspnet/JavaScriptServices#922]
I'm using reactredux AspNetCore spa template and out of the box after restoring dependencies, when running `dotnet run` command I have the following error:
`      ERROR in ./ClientApp/boot-client.tsx
      Module build failed: ReferenceError: Unknown plugin "react-transform" specified in "base" at 0, attempted to resolve relative to "D:\\projects\\dotnet_reactredux\\ClientApp"
          at D:\projects\dotnet_reactredux\node_modules\babel-ore\lib\transformation\file\options\option-manager.js:180:17
at Array.map (native)
at Function.normalisePlugins (D:\projects\dotnet_reactredux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
at OptionManager.mergeOptions (D:\projects\dotnet_reactredux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
at OptionManager.init (D:\projects\dotnet_reactredux\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
at File.initOptions (D:\projects\dotnet_reactredux\node_modules\babel-core\lib\transformation\file\index.js:212:65)
at new File (D:\projects\dotnet_reactredux\node_modules\babel-core\lib\transformation\file\index.js:135:24)
at Pipeline.transform (D:\projects\dotnet_reactredux\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
at transpile (D:\projects\dotnet_reactredux\node_modules\babel-loader\lib\index.js:48:20)
at Object.module.exports (D:\projects\dotnet_reactredux\node_modules\babel-loader\lib\index.js:163:20)@ multi event-source-polyfill webpack-hot-middleware/client?path=%2F__webpack_hmr ./ClientApp/boot-client.tsx`

**Comment by SteveSandersonMS** [comment]
Sorry, I'm not sure how to reproduce this issue. I tried creating a new React+Redux site using the template, but no such error occurred.

Maybe there's a problem with your Node installation. Can you reproduce the problem on a different machine? Do you have any instructions that reproduce the issue on a clean machine?

**Comment by paddyza** [comment]
Sorry, Off Topic: @SteveSandersonMS: Steve your responses are always so friendly, informative and level-headed. Thanks so much for maintaining this repo so well!

**Comment by SteveSandersonMS** [comment]
@paddyza Thanks! That's nice to hear :)

**Comment by aorlenko** [comment]
Steve, there is indeed some issue with environment, because on the other machine the problem was not reproducing. There was another problem with a stale version of babel-loader and parseQuery method, which was gone after babel-loader upgrade to 7.0.0.
Thank you very much!
