### ISSUE TITLE
Generated project doesn't launch or join to solution

### ISSUE THREAD

**Issue by SkyQuant** [aspnet/JavaScriptServices#980]
Can't run or add as existing project on VS 2015

![image](https://cloud.githubusercontent.com/assets/6097882/26466054/04c66ed8-4196-11e7-899c-33cb53a923e5.png)

This is _SpaCore.csproj_ content
```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <!-- Files not to show in IDE -->
    <None Remove="yarn.lock" />

    <!-- Files not to publish (note that the 'dist' subfolders are re-added below) -->
    <Content Remove="ClientApp\**" />
  </ItemGroup>
  <Target Name="RunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec Command="npm install" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --env.prod" />

    <!-- Include the newly-built files in the publish output -->
    <ItemGroup>
      <DistFiles Include="wwwroot\dist\**; ClientApp\dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
```

**Comment by ADefWebserver** [comment]
Please use Visual Studio 2017

**Comment by SkyQuant** [comment]
Nooooooooo! I'm not ready to move to VS2017 right now. Why nobody didn't point this little requirement in documentation.

**Comment by MarkPieszak** [comment]
The generator / templates have moved to 2017 only now.
If you really need 2015 support, you could use older versions of the templates by installing the last working (2015) version. (`v0.8.7`)

    // uninstall previous version
    npm uninstall -g generator-aspnetcore-spa

    // install older version that has the last 2015 templates
    npm install -g yo generator-aspnetcore-spa@0.8.7

Hope that helps! @SkyQuant

**Comment by SkyQuant** [comment]
@MarkPieszak, what does this error mean? I generated project without Yeoman yesterday.
```
PS C:\Apps\TempProjects\MyBot\SpaCore15> yo aspnetcore-spa
module.js:338
    throw err;
          ^
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (mo
    at Function.Module._load (module.js:278
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\generator-aspnetcore-spa\app\index.js:18:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (modul
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310
    at Module.require (module.js:365:17)
PS C:\Apps\TempProjects\MyBot\SpaCore15>
```

**Comment by SteveSandersonMS** [comment]
Thanks for the answer @MarkPieszak.

@SkyQuant Your error about `Cannot find module 'semver'` sounds like either a problem with your network connection, or an issue with NPM itself, or with your Node/NPM installation. If you try again it might just work (if it was a network issue), but in any case it's unrelated to the code in this repo.
