### ISSUE TITLE
Logging to debug 500 Internal Server Error from Webpack Middleware

### ISSUE THREAD

**Issue by jimmcslim** [aspnet/JavaScriptServices#983]
I have a webpack config that works fine from the command line, but throws a 500 (presumably from the Webpack middleware) whenever one of the entry points is accessed by the browser.

The Webpack middleware seems to be bit of a black-box at the moment, would it be possible to expose some of the Node.js instance's output? The 500 response returned empty content.

**Comment by jimmcslim** [comment]
Actually I do get somewhat of an error at startup, although the javascript stack trace is split over several lines so a bit hard to bring back together...

Looks like a call from WebpackDevMiddleware.js into MemoryFileSystem.js - pathToArray is throwing the error.

`
28 May 2017 21:22:52.201
 at C:\Users\james\Source\Workspaces\code\node_modules\webpack\lib\Compiler.js:73:18
28 May 2017 21:22:52.199
 at Watching._done (C:\Users\james\Source\Workspaces\code\node_modules\webpack\lib\Compiler.js:98:16)
28 May 2017 21:22:52.198
 at Compiler.applyPlugins (C:\Users\james\Source\Workspaces\code\node_modules\tapable\lib\Tapable.js:61:14)
28 May 2017 21:22:52.196
 at Compiler.<anonymous> (C:\Users\james\Source\Workspaces\code\node_modules\aspnet-webpack\WebpackDevMiddleware.js:82:9)
28 May 2017 21:22:52.195
 at copyRecursiveToRealFsSync (C:\Users\james\Source\Workspaces\code\node_modules\aspnet-webpack\WebpackDevMiddleware.js:133:31)
28 May 2017 21:22:52.193
 at Array.forEach (native)
28 May 2017 21:22:52.192
 at C:\Users\james\Source\Workspaces\code\node_modules\aspnet-webpack\WebpackDevMiddleware.js:137:33
28 May 2017 21:22:52.191
 at MemoryFileSystem.statSync (C:\Users\james\Source\Workspaces\code\node_modules\memory-fs\lib\MemoryFileSystem.js:76:21)
28 May 2017 21:22:52.161
 at MemoryFileSystem.meta (C:\Users\james\Source\Workspaces\code\node_modules\memory-fs\lib\MemoryFileSystem.js:61:13)
28 May 2017 21:22:52.159
 at pathToArray (C:\Users\james\Source\Workspaces\code\node_modules\memory-fs\lib\MemoryFileSystem.js:44:10)
28 May 2017 21:22:52.157
 Error
28 May 2017 21:22:52.156
 ^
28 May 2017 21:22:52.155
 throw new MemoryFileSystemError(errors.code.EINVAL, path);
28 May 2017 21:22:52.152
 C:\Users\james\Source\Workspaces\code\node_modules\memory-fs\lib\MemoryFileSystem.js:44
`

My webpack.config.js looks like...

`
var Path = require("path");
var Glob = require("glob");

const entries = {};
const files = Glob.sync("./Features/**/*.index.ts?(x)");
files.forEach(file => {
    var name = file.match("./Features(.+[^/]+)\.tsx?$")[1];
    entries[name] = file;
});

module.exports = {
    entry: entries,
    output: {
        filename: "[name].js",
        path: Path.resolve(__dirname, "wwwroot", "app"),
        publicPath: "/app/"
    },
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: "ts-loader",
                exclude: /node_modules/
            }
        ]
    },
    resolve: {
        extensions: [".tsx", ".ts", ".js"]
    }
};
`

I'm scanning my ./Feature folders that contain xxx.index.ts or xxx.index.tsx (in addition to MVC Controllers, Models, etc and aiming to output them to wwwroot/app/

**Comment by jimmcslim** [comment]
Ok, looks like my entries are being generated with names like '/MyFeature1/MyFeature.index.ts' and '/MyFeature2/MyFeature.index.ts'. Webpack on the command line doesn't mind the leading slash, but it gets in the way of the Webpack Dev Server that WebpackMiddleware spawns off.
